<script setup lang="ts">
const source = `import go fmt from "fmt";

function main(): void {
  fmt.Println("Hello from Kinmokusei");
}`;

const generated = `// Code generated by Kinmokusei. DO NOT EDIT.
package main

import fmt "fmt"

func main() {
    fmt.Println("Hello from Kinmokusei")
}`;
</script>

<template>
  <section class="home-showcase" aria-labelledby="showcase-title">
    <div class="home-section-heading">
      <p class="home-eyebrow">ONE SOURCE FILE · ORDINARY GO</p>
      <h2 id="showcase-title">Familiar at the start. Predictable at the boundary.</h2>
      <p>
        Kinmokusei checks the language before generation, then produces formatted Go you can inspect,
        build, test, and publish with the normal Go toolchain.
      </p>
    </div>

    <div class="code-journey">
      <article class="code-window code-window-source">
        <header><span class="window-dot" aria-hidden="true"></span><strong>hello.km</strong><span>Kinmokusei</span></header>
        <pre aria-label="Kinmokusei source"><code>{{ source }}</code></pre>
      </article>

      <div class="journey-arrow" aria-hidden="true"><span>check</span><b>→</b></div>

      <article class="code-window code-window-go">
        <header><span class="window-dot" aria-hidden="true"></span><strong>generated.go</strong><span>Go</span></header>
        <pre aria-label="Generated Go source"><code>{{ generated }}</code></pre>
      </article>
    </div>

    <div class="terminal-result" aria-label="Program output">
      <span class="terminal-prompt" aria-hidden="true">$</span>
      <code>keika run hello.km</code>
      <span class="terminal-output">Hello from Kinmokusei</span>
    </div>
  </section>

  <section class="home-paths" aria-labelledby="path-title">
    <div class="home-section-heading">
      <p class="home-eyebrow">CHOOSE YOUR PATH</p>
      <h2 id="path-title">Start from where you are</h2>
    </div>
    <div class="path-grid">
      <a class="path-card path-new" href="./learn/quick-start">
        <span class="path-icon" aria-hidden="true">01</span>
        <strong>Build your first program</strong>
        <p>Install the toolchain, check one file, run it, and inspect the generated Go.</p>
        <span class="path-link">Five-minute quick start →</span>
      </a>
      <a class="path-card path-ts" href="./learn/from-typescript">
        <span class="path-icon" aria-hidden="true">TS</span>
        <strong>Coming from TypeScript</strong>
        <p>Keep familiar syntax while learning the different runtime, module, error, and task contracts.</p>
        <span class="path-link">Compare the models →</span>
      </a>
      <a class="path-card path-go" href="./learn/from-go">
        <span class="path-icon" aria-hidden="true">Go</span>
        <strong>Coming from Go</strong>
        <p>See how values, packages, errors, channels, and generated APIs preserve Go behavior.</p>
        <span class="path-link">Map the concepts →</span>
      </a>
    </div>
  </section>

  <section class="home-evidence" aria-label="Quality evidence">
    <div><strong>82 / 82</strong><span>Go-equivalent runtime contracts covered by independent oracles</span></div>
    <div><strong>Go 1.23–1.27</strong><span>supported toolchain range for v0.2</span></div>
    <div><strong>0</strong><span>compiler runtime dependencies in published generated Go</span></div>
  </section>
</template>
