package codegen

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"

	ontamaAST "ontama.local/ontama/internal/ast"
	"ontama.local/ontama/internal/product"
)

type cabiScalar struct {
	cType   string
	cgoType string
	goType  string
}

const (
	cabiManifestSchemaVersion = 1
	cabiGatewayVersionMajor   = 1
	cabiGatewayVersionMinor   = 0
)

type CABIOutput struct {
	Gateway     []byte
	Header      []byte
	Manifest    []byte
	Fingerprint string
}

type cabiManifestVersion struct {
	Major int `json:"major"`
	Minor int `json:"minor"`
}

type cabiManifestStatus struct {
	OK              int32 `json:"ok"`
	Panic           int32 `json:"panic"`
	InvalidArgument int32 `json:"invalidArgument"`
}

type cabiManifestFunction struct {
	Symbol          string   `json:"symbol"`
	Parameters      []string `json:"parameters"`
	Result          string   `json:"result"`
	ResultTransport string   `json:"resultTransport"`
}

type cabiFingerprintInput struct {
	SchemaVersion  int                    `json:"schemaVersion"`
	GatewayVersion cabiManifestVersion    `json:"gatewayVersion"`
	Status         cabiManifestStatus     `json:"status"`
	Functions      []cabiManifestFunction `json:"functions"`
}

type cabiManifest struct {
	SchemaVersion  int                    `json:"schemaVersion"`
	GatewayVersion cabiManifestVersion    `json:"gatewayVersion"`
	Fingerprint    string                 `json:"fingerprint"`
	Status         cabiManifestStatus     `json:"status"`
	Functions      []cabiManifestFunction `json:"functions"`
}

// GenerateCABI emits the cgo export gateway and a stable, toolchain-neutral C
// header for explicitly exported OnsenTamago functions. Semantic checking must
// run first; this function still rejects unsupported types defensively.
func GenerateCABI(program *ontamaAST.Program) (CABIOutput, error) {
	exports := cabiExports(program)
	if len(exports) == 0 {
		return CABIOutput{}, fmt.Errorf("program does not declare any C ABI exports")
	}
	manifest, fingerprint, err := generateCABIManifest(exports)
	if err != nil {
		return CABIOutput{}, err
	}

	var goSource strings.Builder
	goSource.WriteString("// Code generated by " + product.DisplayName + ". DO NOT EDIT.\n")
	goSource.WriteString("package main\n\n/*\n#include <stdint.h>\n*/\nimport \"C\"\n\n")

	var cHeader strings.Builder
	cHeader.WriteString("/* Code generated by " + product.DisplayName + ". DO NOT EDIT. */\n")
	cHeader.WriteString("#ifndef ONTAMA_GENERATED_ABI_H\n#define ONTAMA_GENERATED_ABI_H\n\n#include <stdint.h>\n\n")
	cHeader.WriteString("#define ONTAMA_ABI_OK ((int32_t)0)\n")
	cHeader.WriteString("#define ONTAMA_ABI_PANIC ((int32_t)1)\n")
	cHeader.WriteString("#define ONTAMA_ABI_INVALID_ARGUMENT ((int32_t)2)\n")
	fmt.Fprintf(&cHeader, "#define ONTAMA_ABI_GATEWAY_VERSION_MAJOR %d\n", cabiGatewayVersionMajor)
	fmt.Fprintf(&cHeader, "#define ONTAMA_ABI_GATEWAY_VERSION_MINOR %d\n", cabiGatewayVersionMinor)
	fmt.Fprintf(&cHeader, "#define ONTAMA_ABI_FINGERPRINT %q\n\n", fingerprint)
	cHeader.WriteString("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")

	for _, function := range exports {
		if err := generateCABIWrapper(&goSource, &cHeader, function); err != nil {
			return CABIOutput{}, err
		}
	}
	if !hasTopLevelFunction(program, "main") {
		goSource.WriteString("func main() {}\n")
	}
	cHeader.WriteString("#ifdef __cplusplus\n}\n#endif\n\n#endif /* ONTAMA_GENERATED_ABI_H */\n")

	formatted, err := format.Source([]byte(goSource.String()))
	if err != nil {
		return CABIOutput{}, fmt.Errorf("generated C ABI Go gateway failed formatting: %w", err)
	}
	return CABIOutput{Gateway: formatted, Header: []byte(cHeader.String()), Manifest: manifest, Fingerprint: fingerprint}, nil
}

func generateCABIManifest(exports []*ontamaAST.FunctionDecl) ([]byte, string, error) {
	functions := make([]cabiManifestFunction, len(exports))
	for index, function := range exports {
		parameters := make([]string, len(function.Parameters))
		for parameterIndex, parameter := range function.Parameters {
			mapped, ok := mapCABIType(parameter.Type, false)
			if !ok {
				return nil, "", fmt.Errorf("C ABI export %q has unsupported parameter type %q", function.CABISymbol, parameter.Type.Name)
			}
			parameters[parameterIndex] = mapped.cType
		}
		result, ok := mapCABIType(function.ReturnType, true)
		if !ok {
			return nil, "", fmt.Errorf("C ABI export %q has unsupported result type %q", function.CABISymbol, function.ReturnType.Name)
		}
		resultType := result.cType
		transport := "out_parameter"
		if result.goType == "void" {
			resultType = "void"
			transport = "none"
		}
		functions[index] = cabiManifestFunction{
			Symbol: function.CABISymbol, Parameters: parameters, Result: resultType, ResultTransport: transport,
		}
	}
	version := cabiManifestVersion{Major: cabiGatewayVersionMajor, Minor: cabiGatewayVersionMinor}
	status := cabiManifestStatus{OK: 0, Panic: 1, InvalidArgument: 2}
	fingerprintInput := cabiFingerprintInput{
		SchemaVersion: cabiManifestSchemaVersion, GatewayVersion: version, Status: status, Functions: functions,
	}
	canonical, err := json.Marshal(fingerprintInput)
	if err != nil {
		return nil, "", fmt.Errorf("cannot encode C ABI fingerprint input: %w", err)
	}
	digest := sha256.Sum256(canonical)
	fingerprint := "sha256:" + hex.EncodeToString(digest[:])
	manifest := cabiManifest{
		SchemaVersion: cabiManifestSchemaVersion, GatewayVersion: version, Fingerprint: fingerprint, Status: status, Functions: functions,
	}
	encoded, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, "", fmt.Errorf("cannot encode C ABI manifest: %w", err)
	}
	return append(encoded, '\n'), fingerprint, nil
}

func hasTopLevelFunction(program *ontamaAST.Program, name string) bool {
	for _, declaration := range program.Declarations {
		function, ok := declaration.(*ontamaAST.FunctionDecl)
		if ok && function.Name == name {
			return true
		}
	}
	return false
}

func cabiExports(program *ontamaAST.Program) []*ontamaAST.FunctionDecl {
	var exports []*ontamaAST.FunctionDecl
	for _, declaration := range program.Declarations {
		function, ok := declaration.(*ontamaAST.FunctionDecl)
		if ok && function.CABIExport {
			exports = append(exports, function)
		}
	}
	sort.Slice(exports, func(left, right int) bool { return exports[left].CABISymbol < exports[right].CABISymbol })
	return exports
}

func generateCABIWrapper(goSource, cHeader *strings.Builder, function *ontamaAST.FunctionDecl) error {
	parameterTypes := make([]cabiScalar, len(function.Parameters))
	for index, parameter := range function.Parameters {
		mapped, ok := mapCABIType(parameter.Type, false)
		if !ok {
			return fmt.Errorf("C ABI export %q has unsupported parameter type %q", function.CABISymbol, parameter.Type.Name)
		}
		parameterTypes[index] = mapped
	}
	resultType, ok := mapCABIType(function.ReturnType, true)
	if !ok {
		return fmt.Errorf("C ABI export %q has unsupported result type %q", function.CABISymbol, function.ReturnType.Name)
	}

	goSource.WriteString("//export " + function.CABISymbol + "\n")
	goSource.WriteString("func " + function.CABISymbol + "(")
	for index, mapped := range parameterTypes {
		if index != 0 {
			goSource.WriteString(", ")
		}
		fmt.Fprintf(goSource, "arg%d %s", index, mapped.cgoType)
	}
	if resultType.goType != "void" {
		if len(parameterTypes) != 0 {
			goSource.WriteString(", ")
		}
		goSource.WriteString("outResult *" + resultType.cgoType)
	}
	goSource.WriteString(") (__ontamaStatus C.int32_t) {\n")
	goSource.WriteString("\tdefer func() {\n\t\tif recover() != nil {\n\t\t\t__ontamaStatus = C.int32_t(1)\n\t\t}\n\t}()\n")
	if resultType.goType != "void" {
		goSource.WriteString("\tif outResult == nil {\n\t\treturn C.int32_t(2)\n\t}\n")
	}
	if resultType.goType != "void" {
		goSource.WriteString("\t__ontamaResult := ")
	}
	goSource.WriteString(goName(function.Name) + "(")
	for index, mapped := range parameterTypes {
		if index != 0 {
			goSource.WriteString(", ")
		}
		fmt.Fprintf(goSource, "%s(arg%d)", mapped.goType, index)
	}
	goSource.WriteString(")\n")
	if resultType.goType != "void" {
		goSource.WriteString("\t*outResult = " + resultType.cgoType + "(__ontamaResult)\n")
	}
	goSource.WriteString("\treturn C.int32_t(0)\n}\n\n")

	cHeader.WriteString("int32_t " + function.CABISymbol + "(")
	if len(parameterTypes) == 0 && resultType.goType == "void" {
		cHeader.WriteString("void")
	} else {
		for index, mapped := range parameterTypes {
			if index != 0 {
				cHeader.WriteString(", ")
			}
			fmt.Fprintf(cHeader, "%s arg%d", mapped.cType, index)
		}
		if resultType.goType != "void" {
			if len(parameterTypes) != 0 {
				cHeader.WriteString(", ")
			}
			cHeader.WriteString(resultType.cType + " *out_result")
		}
	}
	cHeader.WriteString(");\n")
	return nil
}

func mapCABIType(ref ontamaAST.TypeRef, allowVoid bool) (cabiScalar, bool) {
	if ref.Qualifier != "" || len(ref.GenericArguments) != 0 || ref.IsArray() || ref.IsPointer() || ref.IsFunction() || ref.IsObject() {
		return cabiScalar{}, false
	}
	switch ref.Name {
	case "byte":
		return cabiScalar{cType: "uint8_t", cgoType: "C.uint8_t", goType: "byte"}, true
	case "int32":
		return cabiScalar{cType: "int32_t", cgoType: "C.int32_t", goType: "int32"}, true
	case "int64":
		return cabiScalar{cType: "int64_t", cgoType: "C.int64_t", goType: "int64"}, true
	case "uint16":
		return cabiScalar{cType: "uint16_t", cgoType: "C.uint16_t", goType: "uint16"}, true
	case "uint32":
		return cabiScalar{cType: "uint32_t", cgoType: "C.uint32_t", goType: "uint32"}, true
	case "uint64":
		return cabiScalar{cType: "uint64_t", cgoType: "C.uint64_t", goType: "uint64"}, true
	case "float32":
		return cabiScalar{cType: "float", cgoType: "C.float", goType: "float32"}, true
	case "float", "float64", "number":
		return cabiScalar{cType: "double", cgoType: "C.double", goType: "float64"}, true
	case "void":
		if allowVoid {
			return cabiScalar{goType: "void"}, true
		}
	}
	return cabiScalar{}, false
}
