package codegen

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"

	ontamaAST "github.com/puffball1567/onsentamago/internal/ast"
	"github.com/puffball1567/onsentamago/internal/product"
)

type cabiScalar struct {
	cType   string
	cgoType string
	goType  string
}

const (
	cabiManifestSchemaVersion = 1
	cabiGatewayVersionMajor   = 1
	cabiGatewayVersionMinor   = 0
)

type CABIOutput struct {
	Gateway     []byte
	Header      []byte
	Manifest    []byte
	Fingerprint string
}

type cabiManifestVersion struct {
	Major int `json:"major"`
	Minor int `json:"minor"`
}

type cabiManifestStatus struct {
	OK              int32 `json:"ok"`
	Panic           int32 `json:"panic"`
	InvalidArgument int32 `json:"invalidArgument"`
}

type cabiManifestFunction struct {
	Symbol          string   `json:"symbol"`
	Parameters      []string `json:"parameters"`
	Result          string   `json:"result"`
	ResultTransport string   `json:"resultTransport"`
}

type cabiFingerprintInput struct {
	SchemaVersion  int                    `json:"schemaVersion"`
	GatewayVersion cabiManifestVersion    `json:"gatewayVersion"`
	Status         cabiManifestStatus     `json:"status"`
	Functions      []cabiManifestFunction `json:"functions"`
}

type cabiManifest struct {
	SchemaVersion  int                    `json:"schemaVersion"`
	GatewayVersion cabiManifestVersion    `json:"gatewayVersion"`
	Fingerprint    string                 `json:"fingerprint"`
	Status         cabiManifestStatus     `json:"status"`
	Functions      []cabiManifestFunction `json:"functions"`
}

// GenerateCABI emits the cgo export gateway and a stable, toolchain-neutral C
// header for explicitly exported OnsenTamago functions. Semantic checking must
// run first; this function still rejects unsupported types defensively.
func GenerateCABI(program *ontamaAST.Program) (CABIOutput, error) {
	exports := cabiExports(program)
	if len(exports) == 0 {
		return CABIOutput{}, fmt.Errorf("program does not declare any C ABI exports")
	}
	manifest, fingerprint, err := generateCABIManifest(program, exports)
	if err != nil {
		return CABIOutput{}, err
	}

	var goSource strings.Builder
	goSource.WriteString("// Code generated by " + product.DisplayName + ". DO NOT EDIT.\n")
	goSource.WriteString("package main\n\n/*\n#include <stdint.h>\n*/\nimport \"C\"\n\n")

	var cHeader strings.Builder
	cHeader.WriteString("/* Code generated by " + product.DisplayName + ". DO NOT EDIT. */\n")
	cHeader.WriteString("#ifndef ONTAMA_GENERATED_ABI_H\n#define ONTAMA_GENERATED_ABI_H\n\n#include <stdint.h>\n\n")
	cHeader.WriteString("#define ONTAMA_ABI_OK ((int32_t)0)\n")
	cHeader.WriteString("#define ONTAMA_ABI_PANIC ((int32_t)1)\n")
	cHeader.WriteString("#define ONTAMA_ABI_INVALID_ARGUMENT ((int32_t)2)\n")
	fmt.Fprintf(&cHeader, "#define ONTAMA_ABI_GATEWAY_VERSION_MAJOR %d\n", cabiGatewayVersionMajor)
	fmt.Fprintf(&cHeader, "#define ONTAMA_ABI_GATEWAY_VERSION_MINOR %d\n", cabiGatewayVersionMinor)
	fmt.Fprintf(&cHeader, "#define ONTAMA_ABI_FINGERPRINT %q\n\n", fingerprint)
	cHeader.WriteString("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")

	for _, function := range exports {
		if err := generateCABIWrapper(&goSource, &cHeader, program, function); err != nil {
			return CABIOutput{}, err
		}
	}
	if !hasTopLevelFunction(program, "main") {
		goSource.WriteString("func main() {}\n")
	}
	cHeader.WriteString("#ifdef __cplusplus\n}\n#endif\n\n#endif /* ONTAMA_GENERATED_ABI_H */\n")

	formatted, err := format.Source([]byte(goSource.String()))
	if err != nil {
		return CABIOutput{}, fmt.Errorf("generated C ABI Go gateway failed formatting: %w", err)
	}
	return CABIOutput{Gateway: formatted, Header: []byte(cHeader.String()), Manifest: manifest, Fingerprint: fingerprint}, nil
}

func generateCABIManifest(program *ontamaAST.Program, exports []ontamaAST.CABIExport) ([]byte, string, error) {
	functions := make([]cabiManifestFunction, len(exports))
	for index, export := range exports {
		parameters := make([]string, len(export.Parameters))
		for parameterIndex, parameter := range export.Parameters {
			mapped, ok := mapProgramCABIType(program, parameter.Type, false)
			if !ok {
				return nil, "", fmt.Errorf("C ABI export %q has unsupported parameter type %q", export.Symbol, parameter.Type.Name)
			}
			parameters[parameterIndex] = mapped.cType
		}
		result, ok := mapProgramCABIType(program, export.ReturnType, true)
		if !ok {
			return nil, "", fmt.Errorf("C ABI export %q has unsupported result type %q", export.Symbol, export.ReturnType.Name)
		}
		resultType := result.cType
		transport := "out_parameter"
		if result.goType == "void" {
			resultType = "void"
			transport = "none"
		}
		functions[index] = cabiManifestFunction{
			Symbol: export.Symbol, Parameters: parameters, Result: resultType, ResultTransport: transport,
		}
	}
	version := cabiManifestVersion{Major: cabiGatewayVersionMajor, Minor: cabiGatewayVersionMinor}
	status := cabiManifestStatus{OK: 0, Panic: 1, InvalidArgument: 2}
	fingerprintInput := cabiFingerprintInput{
		SchemaVersion: cabiManifestSchemaVersion, GatewayVersion: version, Status: status, Functions: functions,
	}
	canonical, err := json.Marshal(fingerprintInput)
	if err != nil {
		return nil, "", fmt.Errorf("cannot encode C ABI fingerprint input: %w", err)
	}
	digest := sha256.Sum256(canonical)
	fingerprint := "sha256:" + hex.EncodeToString(digest[:])
	manifest := cabiManifest{
		SchemaVersion: cabiManifestSchemaVersion, GatewayVersion: version, Fingerprint: fingerprint, Status: status, Functions: functions,
	}
	encoded, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, "", fmt.Errorf("cannot encode C ABI manifest: %w", err)
	}
	return append(encoded, '\n'), fingerprint, nil
}

func hasTopLevelFunction(program *ontamaAST.Program, name string) bool {
	for _, declaration := range program.Declarations {
		function, ok := declaration.(*ontamaAST.FunctionDecl)
		if ok && function.Name == name {
			return true
		}
	}
	return false
}

func cabiExports(program *ontamaAST.Program) []ontamaAST.CABIExport {
	exports := append([]ontamaAST.CABIExport(nil), program.CABIExports...)
	sort.Slice(exports, func(left, right int) bool { return exports[left].Symbol < exports[right].Symbol })
	return exports
}

func generateCABIWrapper(goSource, cHeader *strings.Builder, program *ontamaAST.Program, export ontamaAST.CABIExport) error {
	parameterTypes := make([]cabiScalar, len(export.Parameters))
	for index, parameter := range export.Parameters {
		mapped, ok := mapProgramCABIType(program, parameter.Type, false)
		if !ok {
			return fmt.Errorf("C ABI export %q has unsupported parameter type %q", export.Symbol, parameter.Type.Name)
		}
		parameterTypes[index] = mapped
	}
	resultType, ok := mapProgramCABIType(program, export.ReturnType, true)
	if !ok {
		return fmt.Errorf("C ABI export %q has unsupported result type %q", export.Symbol, export.ReturnType.Name)
	}

	goSource.WriteString("//export " + export.Symbol + "\n")
	goSource.WriteString("func " + export.Symbol + "(")
	for index, mapped := range parameterTypes {
		if index != 0 {
			goSource.WriteString(", ")
		}
		fmt.Fprintf(goSource, "arg%d %s", index, mapped.cgoType)
	}
	if resultType.goType != "void" {
		if len(parameterTypes) != 0 {
			goSource.WriteString(", ")
		}
		goSource.WriteString("outResult *" + resultType.cgoType)
	}
	goSource.WriteString(") (__ontamaStatus C.int32_t) {\n")
	goSource.WriteString("\tdefer func() {\n\t\tif recover() != nil {\n\t\t\t__ontamaStatus = C.int32_t(1)\n\t\t}\n\t}()\n")
	if resultType.goType != "void" {
		goSource.WriteString("\tif outResult == nil {\n\t\treturn C.int32_t(2)\n\t}\n")
	}
	if resultType.goType != "void" {
		goSource.WriteString("\t__ontamaResult := ")
	}
	goSource.WriteString(goName(export.Name) + "(")
	for index, mapped := range parameterTypes {
		if index != 0 {
			goSource.WriteString(", ")
		}
		if mapped.goType == "bool" {
			fmt.Fprintf(goSource, "arg%d != 0", index)
		} else {
			fmt.Fprintf(goSource, "%s(arg%d)", mapped.goType, index)
		}
	}
	goSource.WriteString(")\n")
	if resultType.goType != "void" {
		if resultType.goType == "bool" {
			goSource.WriteString("\t*outResult = C.uint8_t(0)\n\tif __ontamaResult {\n\t\t*outResult = C.uint8_t(1)\n\t}\n")
		} else {
			goSource.WriteString("\t*outResult = " + resultType.cgoType + "(__ontamaResult)\n")
		}
	}
	goSource.WriteString("\treturn C.int32_t(0)\n}\n\n")

	cHeader.WriteString("int32_t " + export.Symbol + "(")
	if len(parameterTypes) == 0 && resultType.goType == "void" {
		cHeader.WriteString("void")
	} else {
		for index, mapped := range parameterTypes {
			if index != 0 {
				cHeader.WriteString(", ")
			}
			fmt.Fprintf(cHeader, "%s arg%d", mapped.cType, index)
		}
		if resultType.goType != "void" {
			if len(parameterTypes) != 0 {
				cHeader.WriteString(", ")
			}
			cHeader.WriteString(resultType.cType + " *out_result")
		}
	}
	cHeader.WriteString(");\n")
	return nil
}

func mapCABIType(ref ontamaAST.TypeRef, allowVoid bool) (cabiScalar, bool) {
	if ref.Nullable || ref.Qualifier != "" || len(ref.GenericArguments) != 0 || ref.IsArray() || ref.IsPointer() || ref.IsFunction() || ref.IsObject() {
		return cabiScalar{}, false
	}
	switch ref.Name {
	case "boolean":
		return cabiScalar{cType: "uint8_t", cgoType: "C.uint8_t", goType: "bool"}, true
	case "byte", "uint8":
		return cabiScalar{cType: "uint8_t", cgoType: "C.uint8_t", goType: ref.Name}, true
	case "int8":
		return cabiScalar{cType: "int8_t", cgoType: "C.int8_t", goType: "int8"}, true
	case "int16":
		return cabiScalar{cType: "int16_t", cgoType: "C.int16_t", goType: "int16"}, true
	case "int32":
		return cabiScalar{cType: "int32_t", cgoType: "C.int32_t", goType: "int32"}, true
	case "int64":
		return cabiScalar{cType: "int64_t", cgoType: "C.int64_t", goType: "int64"}, true
	case "uint16":
		return cabiScalar{cType: "uint16_t", cgoType: "C.uint16_t", goType: "uint16"}, true
	case "uint32":
		return cabiScalar{cType: "uint32_t", cgoType: "C.uint32_t", goType: "uint32"}, true
	case "uint64":
		return cabiScalar{cType: "uint64_t", cgoType: "C.uint64_t", goType: "uint64"}, true
	case "float32":
		return cabiScalar{cType: "float", cgoType: "C.float", goType: "float32"}, true
	case "float", "float64", "number":
		return cabiScalar{cType: "double", cgoType: "C.double", goType: "float64"}, true
	case "void":
		if allowVoid {
			return cabiScalar{goType: "void"}, true
		}
	}
	return cabiScalar{}, false
}

func mapProgramCABIType(program *ontamaAST.Program, ref ontamaAST.TypeRef, allowVoid bool) (cabiScalar, bool) {
	if mapped, ok := mapCABIType(ref, allowVoid); ok {
		return mapped, true
	}
	if program == nil || ref.Nullable || ref.Qualifier != "" || len(ref.GenericArguments) != 0 || ref.IsArray() || ref.IsPointer() || ref.IsFunction() || ref.IsObject() {
		return cabiScalar{}, false
	}
	for _, declaration := range program.Declarations {
		enumeration, ok := declaration.(*ontamaAST.EnumDecl)
		if !ok || enumeration.Name != ref.Name {
			continue
		}
		mapped, valid := mapCABIIntegerUnderlying(program, enumeration.Underlying, map[string]bool{enumeration.Name: true})
		if !valid {
			return cabiScalar{}, false
		}
		mapped.goType = ref.Name
		return mapped, true
	}
	return cabiScalar{}, false
}

func mapCABIIntegerUnderlying(program *ontamaAST.Program, ref ontamaAST.TypeRef, visiting map[string]bool) (cabiScalar, bool) {
	if ref.Nullable || ref.Qualifier != "" || len(ref.GenericArguments) != 0 || ref.IsArray() || ref.IsPointer() || ref.IsFunction() || ref.IsObject() {
		return cabiScalar{}, false
	}
	switch ref.Name {
	case "byte", "uint8", "int8", "int16", "int32", "int64", "uint16", "uint32", "uint64":
		return mapCABIType(ref, false)
	}
	if visiting[ref.Name] {
		return cabiScalar{}, false
	}
	visiting[ref.Name] = true
	defer delete(visiting, ref.Name)
	for _, declaration := range program.Declarations {
		switch declaration := declaration.(type) {
		case *ontamaAST.TypeDecl:
			if declaration.Name == ref.Name && len(declaration.TypeParameters) == 0 {
				return mapCABIIntegerUnderlying(program, declaration.Underlying, visiting)
			}
		case *ontamaAST.EnumDecl:
			if declaration.Name == ref.Name {
				return mapCABIIntegerUnderlying(program, declaration.Underlying, visiting)
			}
		}
	}
	return cabiScalar{}, false
}
