package codegen

import (
	"bytes"
	"fmt"
	goast "go/ast"
	"go/format"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"runtime"

	kinmokuseiAST "github.com/puffball1567/kinmokusei/internal/ast"
	"github.com/puffball1567/kinmokusei/internal/product"
)

func Generate(program *kinmokuseiAST.Program, packageName string) ([]byte, error) {
	return GenerateWithImporter(program, packageName, importer.Default())
}

func GenerateWithImporter(program *kinmokuseiAST.Program, packageName string, goImporter types.Importer) ([]byte, error) {
	return GenerateWithTarget(program, packageName, goImporter, nil)
}

// GenerateWithTarget validates against the same target sizes as semantic checking.
func GenerateWithTarget(program *kinmokuseiAST.Program, packageName string, goImporter types.Importer, sizes types.Sizes) ([]byte, error) {
	if packageName == "" {
		packageName = "main"
	}
	file := &goast.File{
		Name: goast.NewIdent(packageName),
	}
	seenImports := map[string]bool{}
	var imports []goast.Spec
	for _, imported := range program.Imports {
		if !imported.Go || !imported.Used || seenImports[imported.Path] {
			continue
		}
		seenImports[imported.Path] = true
		alias := imported.Alias
		if imported.ResolvedAlias != "" {
			alias = imported.ResolvedAlias
		}
		imports = append(imports, &goast.ImportSpec{
			Name: goast.NewIdent(goName(alias)),
			Path: &goast.BasicLit{Kind: token.STRING, Value: fmt.Sprintf("%q", imported.Path)},
		})
	}
	if len(imports) != 0 {
		file.Decls = append(file.Decls, &goast.GenDecl{Tok: token.IMPORT, Specs: imports})
	}
	if program.UsesTasks {
		runtimeDeclarations, err := taskRuntimeDeclarations()
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, runtimeDeclarations...)
	}
	if program.UsesExceptions {
		runtimeDeclarations, err := exceptionRuntimeDeclarations()
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, runtimeDeclarations...)
	}
	if program.UsesDecoratorContext || len(program.Decorators) != 0 {
		file.Decls = append(file.Decls, decoratorRuntimeDeclarations()...)
	}
	for _, decl := range program.Declarations {
		generated, err := generateDeclaration(decl)
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, generated...)
	}
	decoratorInit, err := generateDecoratorInit(program)
	if err != nil {
		return nil, err
	}
	if decoratorInit != nil {
		file.Decls = append(file.Decls, decoratorInit)
	}
	set := token.NewFileSet()
	var output bytes.Buffer
	if err := format.Node(&output, set, file); err != nil {
		return nil, err
	}
	generated := append([]byte("// Code generated by "+product.DisplayName+". DO NOT EDIT.\n"), output.Bytes()...)
	if err := validateGeneratedGoWithTarget(generated, goImporter, sizes); err != nil {
		return nil, fmt.Errorf("generated Go failed validation: %w", err)
	}
	return generated, nil
}

func validateGeneratedGo(generated []byte) error {
	return validateGeneratedGoWithImporter(generated, importer.Default())
}

func validateGeneratedGoWithImporter(generated []byte, goImporter types.Importer) error {
	return validateGeneratedGoWithTarget(generated, goImporter, nil)
}

func validateGeneratedGoWithTarget(generated []byte, goImporter types.Importer, sizes types.Sizes) error {
	files := token.NewFileSet()
	file, err := parser.ParseFile(files, "generated.go", generated, parser.AllErrors)
	if err != nil {
		return err
	}
	if goImporter == nil {
		goImporter = importer.Default()
	}
	if sizes == nil {
		sizes = types.SizesFor("gc", runtime.GOARCH)
	}
	configuration := types.Config{Importer: goImporter, Sizes: sizes}
	_, err = configuration.Check(file.Name.Name, files, []*goast.File{file}, nil)
	return err
}
