package codegen

import (
	"bytes"
	"fmt"
	goast "go/ast"
	"go/format"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"sort"
	"strconv"
	"strings"

	ontamaAST "ontama.local/ontama/internal/ast"
	"ontama.local/ontama/internal/product"
)

func Generate(program *ontamaAST.Program, packageName string) ([]byte, error) {
	return GenerateWithImporter(program, packageName, importer.Default())
}

func GenerateWithImporter(program *ontamaAST.Program, packageName string, goImporter types.Importer) ([]byte, error) {
	if packageName == "" {
		packageName = "main"
	}
	file := &goast.File{
		Name: goast.NewIdent(packageName),
	}
	seenImports := map[string]bool{}
	var imports []goast.Spec
	for _, imported := range program.Imports {
		if !imported.Go || !imported.Used || seenImports[imported.Path] {
			continue
		}
		seenImports[imported.Path] = true
		alias := imported.Alias
		if imported.ResolvedAlias != "" {
			alias = imported.ResolvedAlias
		}
		imports = append(imports, &goast.ImportSpec{
			Name: goast.NewIdent(goName(alias)),
			Path: &goast.BasicLit{Kind: token.STRING, Value: fmt.Sprintf("%q", imported.Path)},
		})
	}
	if len(imports) != 0 {
		file.Decls = append(file.Decls, &goast.GenDecl{Tok: token.IMPORT, Specs: imports})
	}
	if program.UsesTasks {
		runtimeDeclarations, err := taskRuntimeDeclarations()
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, runtimeDeclarations...)
	}
	if program.UsesExceptions {
		runtimeDeclarations, err := exceptionRuntimeDeclarations()
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, runtimeDeclarations...)
	}
	for _, decl := range program.Declarations {
		generated, err := generateDeclaration(decl)
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, generated...)
	}
	set := token.NewFileSet()
	var output bytes.Buffer
	if err := format.Node(&output, set, file); err != nil {
		return nil, err
	}
	generated := append([]byte("// Code generated by "+product.DisplayName+". DO NOT EDIT.\n"), output.Bytes()...)
	if err := validateGeneratedGoWithImporter(generated, goImporter); err != nil {
		return nil, fmt.Errorf("generated Go failed validation: %w", err)
	}
	return generated, nil
}

func taskRuntimeDeclarations() ([]goast.Decl, error) {
	const runtimeSource = `package taskruntime
type __ontamaTask[T any] struct { done chan struct{}; value T; panicValue any }
type __ontamaVoidTask struct { done chan struct{}; panicValue any }
type __ontamaResultTask[T any] struct { done chan struct{}; value T; err error; panicValue any }
type __ontamaVoidResultTask struct { done chan struct{}; err error; panicValue any }
`
	parsed, err := parser.ParseFile(token.NewFileSet(), "task_runtime.go", runtimeSource, parser.AllErrors)
	if err != nil {
		return nil, fmt.Errorf("parse internal task runtime: %w", err)
	}
	return parsed.Decls, nil
}

func exceptionRuntimeDeclarations() ([]goast.Decl, error) {
	const runtimeSource = `package exceptionruntime
type __ontamaException interface { OnsenTamagoExceptionError() error }
type __ontamaThrown struct { err error }
func (value __ontamaThrown) OnsenTamagoExceptionError() error { return value.err }
type __ontamaReturn struct { value any; err error }
func __ontamaReturnValue[T any](value any) T {
	if value == nil { var zero T; return zero }
	return value.(T)
}
type Exception struct { __ontamaRoot any; Message string }
func __ontamaInitException(this *Exception, message string) { this.Message = message; this.__ontamaRoot = this }
func NewException(message string) *Exception { this := &Exception{}; __ontamaInitException(this, message); return this }
func (this *Exception) Error() string { return this.Message }
func __ontamaExceptionFromError(err error) *Exception {
	if value, ok := err.(*Exception); ok { return value }
	if err == nil { return NewException("") }
	return NewException(err.Error())
}
`
	parsed, err := parser.ParseFile(token.NewFileSet(), "exception_runtime.go", runtimeSource, parser.AllErrors)
	if err != nil {
		return nil, fmt.Errorf("parse internal exception runtime: %w", err)
	}
	return parsed.Decls, nil
}

func validateGeneratedGo(generated []byte) error {
	return validateGeneratedGoWithImporter(generated, importer.Default())
}

func validateGeneratedGoWithImporter(generated []byte, goImporter types.Importer) error {
	files := token.NewFileSet()
	file, err := parser.ParseFile(files, "generated.go", generated, parser.AllErrors)
	if err != nil {
		return err
	}
	if goImporter == nil {
		goImporter = importer.Default()
	}
	configuration := types.Config{Importer: goImporter}
	_, err = configuration.Check(file.Name.Name, files, []*goast.File{file}, nil)
	return err
}

func generateDeclaration(decl ontamaAST.Declaration) ([]goast.Decl, error) {
	switch decl := decl.(type) {
	case *ontamaAST.FunctionDecl:
		params := make([]*goast.Field, 0, len(decl.Parameters))
		for _, param := range decl.Parameters {
			params = append(params, goParameterField(param))
		}
		fnType := &goast.FuncType{Params: &goast.FieldList{List: params}}
		if len(decl.TypeParameters) != 0 {
			typeParameters := make([]*goast.Field, 0, len(decl.TypeParameters))
			for _, parameter := range decl.TypeParameters {
				typeParameters = append(typeParameters, goTypeParameterField(parameter, false))
			}
			fnType.TypeParams = &goast.FieldList{List: typeParameters}
		}
		fnType.Results = functionResults(decl.ReturnType)
		body, err := generateBlock(decl.Body)
		if err != nil {
			return nil, err
		}
		return []goast.Decl{&goast.FuncDecl{Name: goast.NewIdent(goName(decl.Name)), Type: fnType, Body: body}}, nil
	case *ontamaAST.MethodDecl:
		generated, err := generateNativeStructMethod(decl, decl.ReceiverName, goType(decl.ReceiverType))
		if err != nil {
			return nil, err
		}
		return []goast.Decl{generated}, nil
	case *ontamaAST.VariableDecl:
		value, err := generateExpression(decl.Value)
		if err != nil {
			return nil, err
		}
		tok := token.VAR
		if decl.Constant && isGoConstant(decl.Value) {
			tok = token.CONST
		}
		spec := &goast.ValueSpec{Names: []*goast.Ident{goast.NewIdent(goName(decl.Name))}, Values: []goast.Expr{value}}
		if decl.Type.Name != "" || decl.Type.IsFunction() || decl.Type.IsPointer() {
			spec.Type = goType(decl.Type)
		}
		return []goast.Decl{&goast.GenDecl{Tok: tok, Specs: []goast.Spec{spec}}}, nil
	case *ontamaAST.CABIExportDecl:
		return nil, nil
	case *ontamaAST.ClassDecl:
		return generateClass(decl)
	case *ontamaAST.StructDecl:
		fields := make([]*goast.Field, 0, len(decl.Fields))
		for _, field := range decl.Fields {
			name := field.GoName
			if name == "" {
				name = memberName(field.Name, field.Visibility)
			}
			fields = append(fields, &goast.Field{Names: []*goast.Ident{goast.NewIdent(goName(name))}, Type: goType(field.Type)})
		}
		typeSpec := &goast.TypeSpec{Name: goast.NewIdent(decl.Name), Type: &goast.StructType{Fields: &goast.FieldList{List: fields}}}
		if len(decl.TypeParameters) != 0 {
			typeFields := make([]*goast.Field, 0, len(decl.TypeParameters))
			for _, parameter := range decl.TypeParameters {
				typeFields = append(typeFields, goTypeParameterField(parameter, false))
			}
			typeSpec.TypeParams = &goast.FieldList{List: typeFields}
		}
		declarations := []goast.Decl{&goast.GenDecl{Tok: token.TYPE, Specs: []goast.Spec{typeSpec}}}
		receiverArguments := make([]goast.Expr, len(decl.TypeParameters))
		for index, parameter := range decl.TypeParameters {
			receiverArguments[index] = goast.NewIdent(parameter.Name)
		}
		for _, method := range decl.Methods {
			receiver := goast.Expr(goast.NewIdent(decl.Name))
			if len(receiverArguments) == 1 {
				receiver = &goast.IndexExpr{X: receiver, Index: receiverArguments[0]}
			} else if len(receiverArguments) > 1 {
				receiver = &goast.IndexListExpr{X: receiver, Indices: receiverArguments}
			}
			if method.PointerReceiver {
				receiver = &goast.StarExpr{X: receiver}
			}
			generated, err := generateNativeStructMethod(method, "this", receiver)
			if err != nil {
				return nil, err
			}
			declarations = append(declarations, generated)
		}
		return declarations, nil
	case *ontamaAST.TypeDecl:
		spec := &goast.TypeSpec{Name: goast.NewIdent(decl.Name), Type: goType(decl.Underlying)}
		if decl.Alias {
			spec.Assign = token.Pos(1)
		}
		if len(decl.TypeParameters) != 0 {
			typeFields := make([]*goast.Field, 0, len(decl.TypeParameters))
			comparable := comparableTypeParameters(decl.Underlying)
			for _, parameter := range decl.TypeParameters {
				typeFields = append(typeFields, goTypeParameterField(parameter, comparable[parameter.Name]))
			}
			spec.TypeParams = &goast.FieldList{List: typeFields}
		}
		return []goast.Decl{&goast.GenDecl{Tok: token.TYPE, Specs: []goast.Spec{spec}}}, nil
	case *ontamaAST.EnumDecl:
		typeDeclaration := &goast.GenDecl{Tok: token.TYPE, Specs: []goast.Spec{&goast.TypeSpec{
			Name: goast.NewIdent(decl.Name), Type: goType(decl.Underlying),
		}}}
		constants := make([]goast.Spec, 0, len(decl.Members))
		for _, member := range decl.Members {
			constants = append(constants, &goast.ValueSpec{
				Names:  []*goast.Ident{goast.NewIdent(enumMemberGoName(decl.Name, member.Name))},
				Type:   goast.NewIdent(decl.Name),
				Values: []goast.Expr{goIntegerConstant(member.ResolvedValue)},
			})
		}
		return []goast.Decl{typeDeclaration, &goast.GenDecl{Tok: token.CONST, Specs: constants}}, nil
	case *ontamaAST.InterfaceDecl:
		methods := make([]*goast.Field, 0, len(decl.Methods))
		for _, method := range decl.Methods {
			parameters := make([]*goast.Field, 0, len(method.Parameters))
			for _, parameter := range method.Parameters {
				parameters = append(parameters, goParameterField(parameter))
			}
			methodType := &goast.FuncType{Params: &goast.FieldList{List: parameters}}
			methodType.Results = functionResults(method.ReturnType)
			name := method.GoName
			if name == "" {
				name = memberName(method.Name, ontamaAST.Public)
			}
			methods = append(methods, &goast.Field{Names: []*goast.Ident{goast.NewIdent(name)}, Type: methodType})
		}
		typeSpec := &goast.TypeSpec{Name: goast.NewIdent(decl.Name), Type: &goast.InterfaceType{Methods: &goast.FieldList{List: methods}}}
		if len(decl.TypeParameters) != 0 {
			typeFields := make([]*goast.Field, 0, len(decl.TypeParameters))
			for _, parameter := range decl.TypeParameters {
				typeFields = append(typeFields, goTypeParameterField(parameter, false))
			}
			typeSpec.TypeParams = &goast.FieldList{List: typeFields}
		}
		return []goast.Decl{&goast.GenDecl{Tok: token.TYPE, Specs: []goast.Spec{typeSpec}}}, nil
	default:
		return nil, fmt.Errorf("unsupported declaration %T", decl)
	}
}

func goTypeParameterField(parameter ontamaAST.TypeParameter, inferredComparable bool) *goast.Field {
	constraint := "any"
	if inferredComparable || parameter.Constraint != nil && parameter.Constraint.Name == "comparable" {
		constraint = "comparable"
	}
	return &goast.Field{
		Names: []*goast.Ident{goast.NewIdent(goName(parameter.Name))},
		Type:  goast.NewIdent(constraint),
	}
}

func comparableTypeParameters(ref ontamaAST.TypeRef) map[string]bool {
	result := map[string]bool{}
	collectComparableTypeParameters(ref, result)
	return result
}

func collectComparableTypeParameters(ref ontamaAST.TypeRef, result map[string]bool) {
	if ref.Name == "Map" && len(ref.GenericArguments) == 2 {
		collectTypeParametersRequiringComparability(ref.GenericArguments[0], result)
	}
	if ref.Element != nil {
		collectComparableTypeParameters(*ref.Element, result)
	}
	if ref.Pointee != nil {
		collectComparableTypeParameters(*ref.Pointee, result)
	}
	for _, argument := range ref.GenericArguments {
		collectComparableTypeParameters(argument, result)
	}
	for _, parameter := range ref.Parameters {
		collectComparableTypeParameters(parameter, result)
	}
	if ref.Return != nil {
		collectComparableTypeParameters(*ref.Return, result)
	}
	for _, field := range ref.ObjectFields {
		collectComparableTypeParameters(field.Type, result)
	}
}

func collectTypeParametersRequiringComparability(ref ontamaAST.TypeRef, result map[string]bool) {
	if ref.IsPointer() || ref.IsSlice() || ref.Name == "Map" || ref.IsFunction() || ref.Object || ref.GoStruct {
		return
	}
	if len(ref.GenericArguments) == 0 && ref.Element == nil {
		result[ref.Name] = true
		return
	}
	if ref.Element != nil {
		collectTypeParametersRequiringComparability(*ref.Element, result)
	}
	for _, argument := range ref.GenericArguments {
		collectTypeParametersRequiringComparability(argument, result)
	}
}

func goParameterField(parameter ontamaAST.Parameter) *goast.Field {
	parameterType := goType(parameter.Type)
	if parameter.Variadic && parameter.Type.Element != nil {
		parameterType = &goast.Ellipsis{Elt: goType(*parameter.Type.Element)}
	}
	return &goast.Field{
		Names: []*goast.Ident{goast.NewIdent(goName(parameter.Name))},
		Type:  parameterType,
	}
}

func generateNativeStructMethod(method *ontamaAST.MethodDecl, receiverName string, receiver goast.Expr) (*goast.FuncDecl, error) {
	parameters := make([]*goast.Field, 0, len(method.Parameters))
	for _, parameter := range method.Parameters {
		parameters = append(parameters, goParameterField(parameter))
	}
	methodType := &goast.FuncType{Params: &goast.FieldList{List: parameters}, Results: functionResults(method.ReturnType)}
	body, err := generateBlock(method.Body)
	if err != nil {
		return nil, err
	}
	name := method.GoName
	if name == "" {
		name = memberName(method.Name, method.Visibility)
	}
	return &goast.FuncDecl{
		Recv: &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent(goName(receiverName))}, Type: receiver}}},
		Name: goast.NewIdent(goName(name)), Type: methodType, Body: body,
	}, nil
}

func generateClass(class *ontamaAST.ClassDecl) ([]goast.Decl, error) {
	var declarations []goast.Decl
	typeParameterFields := make([]*goast.Field, 0, len(class.TypeParameters))
	for _, parameter := range class.TypeParameters {
		typeParameterFields = append(typeParameterFields, goTypeParameterField(parameter, false))
	}
	classType := indexedGoType(goast.NewIdent(class.Name), typeRefsForTypeParameters(class.TypeParameters))
	classPointer := &goast.StarExpr{X: classType}
	for _, method := range class.Methods {
		if !method.Virtual || method.Override || method.Static {
			continue
		}
		parameters := make([]*goast.Field, 0, len(method.Parameters))
		for _, parameter := range method.Parameters {
			parameters = append(parameters, goParameterField(parameter))
		}
		methodType := &goast.FuncType{Params: &goast.FieldList{List: parameters}, Results: functionResults(method.ReturnType)}
		name := method.GoName
		if name == "" {
			name = memberName(method.Name, method.Visibility)
		}
		name = virtualSlotName(class.Name, name)
		interfaceName := virtualInterfaceName(class.Name)
		if len(declarations) != 0 {
			if declaration, ok := declarations[len(declarations)-1].(*goast.GenDecl); ok {
				if specification, ok := declaration.Specs[0].(*goast.TypeSpec); ok && specification.Name.Name == interfaceName {
					specification.Type.(*goast.InterfaceType).Methods.List = append(specification.Type.(*goast.InterfaceType).Methods.List, &goast.Field{Names: []*goast.Ident{goast.NewIdent(name)}, Type: methodType})
					continue
				}
			}
		}
		declarations = append(declarations, &goast.GenDecl{Tok: token.TYPE, Specs: []goast.Spec{&goast.TypeSpec{
			Name: goast.NewIdent(interfaceName), Type: &goast.InterfaceType{Methods: &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent(name)}, Type: methodType}}}},
		}}})
	}

	fields := make([]*goast.Field, 0, len(class.Fields)+2)
	if class.Base != nil {
		fields = append(fields, &goast.Field{Type: goast.NewIdent(class.Base.Name)})
	}
	if class.HierarchyRoot == class.Name {
		fields = append(fields, &goast.Field{Names: []*goast.Ident{goast.NewIdent(classRootName())}, Type: goast.NewIdent("any")})
	}
	for _, owner := range class.VirtualOwners {
		if owner == class.Name {
			fields = append(fields, &goast.Field{Names: []*goast.Ident{goast.NewIdent(virtualSelfName(owner))}, Type: goast.NewIdent(virtualInterfaceName(owner))})
		}
	}
	for _, field := range class.Fields {
		name := field.GoName
		if name == "" {
			name = memberName(field.Name, field.Visibility)
		}
		fields = append(fields, &goast.Field{Names: []*goast.Ident{goast.NewIdent(goName(name))}, Type: goType(field.Type)})
	}
	if class.Constructor != nil {
		for _, parameter := range class.Constructor.Parameters {
			if parameter.IsField {
				fields = append(fields, &goast.Field{Names: []*goast.Ident{goast.NewIdent(goName(memberName(parameter.Name, parameter.Visibility)))}, Type: goType(parameter.Type)})
			}
		}
	}
	classSpec := &goast.TypeSpec{Name: goast.NewIdent(class.Name), Type: &goast.StructType{Fields: &goast.FieldList{List: fields}}}
	if len(typeParameterFields) != 0 {
		classSpec.TypeParams = &goast.FieldList{List: typeParameterFields}
	}
	declarations = append(declarations, &goast.GenDecl{Tok: token.TYPE, Specs: []goast.Spec{classSpec}})
	for ancestorIndex, ancestor := range class.Ancestors {
		selected := goast.Expr(goast.NewIdent("value"))
		for index := 0; index <= ancestorIndex; index++ {
			selected = &goast.SelectorExpr{X: selected, Sel: goast.NewIdent(class.Ancestors[index])}
		}
		declarations = append(declarations, &goast.FuncDecl{
			Name: goast.NewIdent(upcastName(class.Name, ancestor)),
			Type: &goast.FuncType{
				Params:  &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent("value")}, Type: &goast.StarExpr{X: goast.NewIdent(class.Name)}}}},
				Results: &goast.FieldList{List: []*goast.Field{{Type: &goast.StarExpr{X: goast.NewIdent(ancestor)}}}},
			},
			Body: &goast.BlockStmt{List: []goast.Stmt{
				&goast.IfStmt{Cond: &goast.BinaryExpr{X: goast.NewIdent("value"), Op: token.EQL, Y: goast.NewIdent("nil")}, Body: &goast.BlockStmt{List: []goast.Stmt{&goast.ReturnStmt{Results: []goast.Expr{goast.NewIdent("nil")}}}}},
				&goast.ReturnStmt{Results: []goast.Expr{&goast.UnaryExpr{Op: token.AND, X: selected}}},
			}},
		})
		checkedType := &goast.FuncType{
			Params:  &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent("value")}, Type: &goast.StarExpr{X: goast.NewIdent(ancestor)}}}},
			Results: &goast.FieldList{List: []*goast.Field{{Type: &goast.StarExpr{X: goast.NewIdent(class.Name)}}, {Type: goast.NewIdent("bool")}}},
		}
		checkedBody := &goast.BlockStmt{List: []goast.Stmt{
			&goast.IfStmt{Cond: &goast.BinaryExpr{X: goast.NewIdent("value"), Op: token.EQL, Y: goast.NewIdent("nil")}, Body: &goast.BlockStmt{List: []goast.Stmt{&goast.ReturnStmt{Results: []goast.Expr{goast.NewIdent("nil"), goast.NewIdent("false")}}}}},
		}}
		candidates := append([]string{class.Name}, class.Descendants...)
		for _, candidate := range candidates {
			assertion := &goast.TypeAssertExpr{X: &goast.SelectorExpr{X: goast.NewIdent("value"), Sel: goast.NewIdent(classRootName())}, Type: &goast.StarExpr{X: goast.NewIdent(candidate)}}
			result := goast.Expr(goast.NewIdent("result"))
			if candidate != class.Name {
				result = &goast.CallExpr{Fun: goast.NewIdent(upcastName(candidate, class.Name)), Args: []goast.Expr{goast.NewIdent("result")}}
			}
			checkedBody.List = append(checkedBody.List, &goast.IfStmt{
				Init: &goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent("result"), goast.NewIdent("ok")}, Tok: token.DEFINE, Rhs: []goast.Expr{assertion}},
				Cond: goast.NewIdent("ok"), Body: &goast.BlockStmt{List: []goast.Stmt{&goast.ReturnStmt{Results: []goast.Expr{result, goast.NewIdent("true")}}}},
			})
		}
		checkedBody.List = append(checkedBody.List, &goast.ReturnStmt{Results: []goast.Expr{goast.NewIdent("nil"), goast.NewIdent("false")}})
		declarations = append(declarations, &goast.FuncDecl{
			Name: goast.NewIdent(downcastName(ancestor, class.Name)), Type: checkedType,
			Body: checkedBody,
		})
		declarations = append(declarations, &goast.FuncDecl{
			Name: goast.NewIdent(mustDowncastName(ancestor, class.Name)),
			Type: &goast.FuncType{
				Params:  &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent("value")}, Type: &goast.StarExpr{X: goast.NewIdent(ancestor)}}}},
				Results: &goast.FieldList{List: []*goast.Field{{Type: &goast.StarExpr{X: goast.NewIdent(class.Name)}}}},
			},
			Body: &goast.BlockStmt{List: []goast.Stmt{
				&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent("result"), goast.NewIdent("ok")}, Tok: token.DEFINE, Rhs: []goast.Expr{&goast.CallExpr{Fun: goast.NewIdent(downcastName(ancestor, class.Name)), Args: []goast.Expr{goast.NewIdent("value")}}}},
				&goast.IfStmt{Cond: &goast.UnaryExpr{Op: token.NOT, X: goast.NewIdent("ok")}, Body: &goast.BlockStmt{List: []goast.Stmt{&goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent("panic"), Args: []goast.Expr{&goast.BasicLit{Kind: token.STRING, Value: strconv.Quote("cannot downcast " + ancestor + " to " + class.Name)}}}}}}},
				&goast.ReturnStmt{Results: []goast.Expr{goast.NewIdent("result")}},
			}},
		})
		declarations = append(declarations,
			generateConversionWrapper(publicUpcastName(class.Name, ancestor), upcastName(class.Name, ancestor), class.Name, ancestor, false),
			generateConversionWrapper(publicDowncastName(ancestor, class.Name), downcastName(ancestor, class.Name), ancestor, class.Name, true),
			generateConversionWrapper(publicMustDowncastName(ancestor, class.Name), mustDowncastName(ancestor, class.Name), ancestor, class.Name, false),
		)
	}
	for _, implemented := range class.Implements {
		if len(class.TypeParameters) != 0 {
			continue
		}
		declarations = append(declarations, &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{
			Names: []*goast.Ident{goast.NewIdent("_")}, Type: goType(implemented),
			Values: []goast.Expr{&goast.UnaryExpr{Op: token.AND, X: &goast.CompositeLit{Type: goast.NewIdent(class.Name)}}},
		}}})
	}

	constructorType := &goast.FuncType{Params: &goast.FieldList{}}
	initializerType := &goast.FuncType{Params: &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent("this")}, Type: classPointer}}}}
	if len(typeParameterFields) != 0 {
		initializerType.TypeParams = &goast.FieldList{List: typeParameterFields}
	}
	var constructorParameters []ontamaAST.Parameter
	if class.Constructor != nil {
		constructorParameters = class.Constructor.Parameters
	}
	for _, parameter := range constructorParameters {
		field := goParameterField(parameter)
		constructorType.Params.List = append(constructorType.Params.List, field)
		initializerType.Params.List = append(initializerType.Params.List, goParameterField(parameter))
	}
	initializerBody := &goast.BlockStmt{}
	constructorStatements := []ontamaAST.Statement(nil)
	if class.Constructor != nil {
		constructorStatements = class.Constructor.Body.Statements
	}
	if class.Base != nil {
		var baseCall goast.Stmt
		if len(constructorStatements) != 0 {
			if expression, ok := constructorStatements[0].(*ontamaAST.ExpressionStmt); ok {
				if call, ok := expression.Value.(*ontamaAST.CallExpr); ok && call.SuperConstructor {
					generated, err := generateExpression(call)
					if err != nil {
						return nil, err
					}
					baseCall = &goast.ExprStmt{X: generated}
					constructorStatements = constructorStatements[1:]
				}
			}
		}
		if baseCall == nil {
			baseCall = &goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent(initializerName(class.Base.Name)), Args: []goast.Expr{&goast.UnaryExpr{Op: token.AND, X: &goast.SelectorExpr{X: goast.NewIdent("this"), Sel: goast.NewIdent(class.Base.Name)}}}}}
		}
		initializerBody.List = append(initializerBody.List, baseCall)
	}
	for _, parameter := range constructorParameters {
		if parameter.IsField {
			initializerBody.List = append(initializerBody.List, &goast.AssignStmt{
				Lhs: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("this"), Sel: goast.NewIdent(goName(memberName(parameter.Name, parameter.Visibility)))}}, Tok: token.ASSIGN,
				Rhs: []goast.Expr{goast.NewIdent(goName(parameter.Name))},
			})
		}
	}
	for _, owner := range class.VirtualOwners {
		initializerBody.List = append(initializerBody.List, &goast.AssignStmt{
			Lhs: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("this"), Sel: goast.NewIdent(virtualSelfName(owner))}}, Tok: token.ASSIGN,
			Rhs: []goast.Expr{goast.NewIdent("this")},
		})
	}
	if class.HierarchyRoot != "" {
		initializerBody.List = append(initializerBody.List, &goast.AssignStmt{
			Lhs: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("this"), Sel: goast.NewIdent(classRootName())}}, Tok: token.ASSIGN,
			Rhs: []goast.Expr{goast.NewIdent("this")},
		})
	}
	if len(constructorStatements) != 0 {
		body, err := generateBlock(&ontamaAST.BlockStmt{Statements: constructorStatements})
		if err != nil {
			return nil, err
		}
		initializerBody.List = append(initializerBody.List, body.List...)
	}
	declarations = append(declarations, &goast.FuncDecl{Name: goast.NewIdent(initializerName(class.Name)), Type: initializerType, Body: initializerBody})

	if len(typeParameterFields) != 0 {
		constructorType.TypeParams = &goast.FieldList{List: typeParameterFields}
	}
	constructorType.Results = &goast.FieldList{List: []*goast.Field{{Type: classPointer}}}
	constructorBody := &goast.BlockStmt{}
	constructorBody.List = append(constructorBody.List, &goast.AssignStmt{
		Lhs: []goast.Expr{goast.NewIdent("this")}, Tok: token.DEFINE,
		Rhs: []goast.Expr{&goast.UnaryExpr{Op: token.AND, X: &goast.CompositeLit{Type: classType}}},
	})
	initializerArguments := []goast.Expr{goast.NewIdent("this")}
	for _, parameter := range constructorParameters {
		initializerArguments = append(initializerArguments, goast.NewIdent(goName(parameter.Name)))
	}
	initializerCall := &goast.CallExpr{Fun: goast.NewIdent(initializerName(class.Name)), Args: initializerArguments}
	if len(constructorParameters) != 0 && constructorParameters[len(constructorParameters)-1].Variadic {
		initializerCall.Ellipsis = token.Pos(1)
	}
	constructorBody.List = append(constructorBody.List, &goast.ExprStmt{X: initializerCall})
	constructorBody.List = append(constructorBody.List, &goast.ReturnStmt{Results: []goast.Expr{goast.NewIdent("this")}})
	declarations = append(declarations, &goast.FuncDecl{
		Name: goast.NewIdent("New" + class.Name), Type: constructorType, Body: constructorBody,
	})

	for _, method := range class.Methods {
		parameters := make([]*goast.Field, 0, len(method.Parameters))
		for _, parameter := range method.Parameters {
			parameters = append(parameters, goParameterField(parameter))
		}
		methodType := &goast.FuncType{Params: &goast.FieldList{List: parameters}}
		methodType.Results = functionResults(method.ReturnType)
		body, err := generateBlock(method.Body)
		if err != nil {
			return nil, err
		}
		name := method.GoName
		if name == "" {
			name = memberName(method.Name, method.Visibility)
		}
		generated := &goast.FuncDecl{Name: goast.NewIdent(goName(name)), Type: methodType, Body: body}
		if method.Static {
			generated.Name = goast.NewIdent(staticMethodName(class.Name, name, method.Visibility))
		} else {
			generated.Recv = &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent("this")}, Type: classPointer}}}
			if method.Virtual || method.Override {
				generated.Name = goast.NewIdent(virtualSlotName(method.VirtualOwner, name))
				if method.Virtual && !method.Override {
					declarations = append(declarations, generateVirtualWrapper(class.Name, method, name))
				}
			}
		}
		declarations = append(declarations, generated)
	}
	return declarations, nil
}

func typeRefsForTypeParameters(parameters []ontamaAST.TypeParameter) []ontamaAST.TypeRef {
	result := make([]ontamaAST.TypeRef, len(parameters))
	for index, parameter := range parameters {
		result[index] = ontamaAST.TypeRef{Name: parameter.Name, TypeParameter: true, Span: parameter.Span}
	}
	return result
}

func generateVirtualWrapper(className string, method *ontamaAST.MethodDecl, name string) *goast.FuncDecl {
	parameters := make([]*goast.Field, 0, len(method.Parameters))
	arguments := make([]goast.Expr, 0, len(method.Parameters))
	for _, parameter := range method.Parameters {
		parameterName := goName(parameter.Name)
		parameters = append(parameters, goParameterField(parameter))
		arguments = append(arguments, goast.NewIdent(parameterName))
	}
	methodType := &goast.FuncType{Params: &goast.FieldList{List: parameters}, Results: functionResults(method.ReturnType)}
	directCall := &goast.CallExpr{
		Fun:  &goast.SelectorExpr{X: goast.NewIdent("this"), Sel: goast.NewIdent(virtualSlotName(className, name))},
		Args: arguments,
	}
	dispatchCall := &goast.CallExpr{
		Fun: &goast.SelectorExpr{
			X:   &goast.SelectorExpr{X: goast.NewIdent("this"), Sel: goast.NewIdent(virtualSelfName(className))},
			Sel: goast.NewIdent(virtualSlotName(className, name)),
		},
		Args: arguments,
	}
	if len(method.Parameters) != 0 && method.Parameters[len(method.Parameters)-1].Variadic {
		directCall.Ellipsis = token.Pos(1)
		dispatchCall.Ellipsis = token.Pos(1)
	}
	condition := &goast.BinaryExpr{
		X:  &goast.BinaryExpr{X: goast.NewIdent("this"), Op: token.EQL, Y: goast.NewIdent("nil")},
		Op: token.LOR,
		Y: &goast.BinaryExpr{
			X:  &goast.SelectorExpr{X: goast.NewIdent("this"), Sel: goast.NewIdent(virtualSelfName(className))},
			Op: token.EQL, Y: goast.NewIdent("nil"),
		},
	}
	body := &goast.BlockStmt{}
	if method.ReturnType.Name == "void" {
		body.List = append(body.List,
			&goast.IfStmt{Cond: condition, Body: &goast.BlockStmt{List: []goast.Stmt{
				&goast.ExprStmt{X: directCall}, &goast.ReturnStmt{},
			}}},
			&goast.ExprStmt{X: dispatchCall},
		)
	} else {
		body.List = append(body.List,
			&goast.IfStmt{Cond: condition, Body: &goast.BlockStmt{List: []goast.Stmt{
				&goast.ReturnStmt{Results: []goast.Expr{directCall}},
			}}},
			&goast.ReturnStmt{Results: []goast.Expr{dispatchCall}},
		)
	}
	return &goast.FuncDecl{
		Recv: &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent("this")}, Type: &goast.StarExpr{X: goast.NewIdent(className)}}}},
		Name: goast.NewIdent(goName(name)), Type: methodType, Body: body,
	}
}

func virtualInterfaceName(className string) string { return "__ontama" + className + "Virtual" }
func virtualSelfName(className string) string      { return "__ontama" + className + "Self" }
func virtualSlotName(owner, method string) string  { return "__ontama" + owner + method }
func initializerName(className string) string      { return "__ontamaInit" + className }
func upcastName(source, target string) string      { return "__ontamaUpcast" + source + "To" + target }
func downcastName(source, target string) string    { return "__ontamaDowncast" + source + "To" + target }
func mustDowncastName(source, target string) string {
	return "__ontamaMustDowncast" + source + "To" + target
}
func publicUpcastName(source, target string) string   { return "Upcast" + source + "To" + target }
func publicDowncastName(source, target string) string { return "Downcast" + source + "To" + target }
func publicMustDowncastName(source, target string) string {
	return "MustDowncast" + source + "To" + target
}
func classRootName() string { return "__ontamaRoot" }

func generateConversionWrapper(name, implementation, source, target string, checked bool) *goast.FuncDecl {
	results := []*goast.Field{{Type: &goast.StarExpr{X: goast.NewIdent(target)}}}
	if checked {
		results = append(results, &goast.Field{Type: goast.NewIdent("bool")})
	}
	return &goast.FuncDecl{
		Name: goast.NewIdent(name),
		Type: &goast.FuncType{
			Params:  &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent("value")}, Type: &goast.StarExpr{X: goast.NewIdent(source)}}}},
			Results: &goast.FieldList{List: results},
		},
		Body: &goast.BlockStmt{List: []goast.Stmt{&goast.ReturnStmt{Results: []goast.Expr{&goast.CallExpr{
			Fun: goast.NewIdent(implementation), Args: []goast.Expr{goast.NewIdent("value")},
		}}}}},
	}
}

func generateBlock(block *ontamaAST.BlockStmt) (*goast.BlockStmt, error) {
	result := &goast.BlockStmt{}
	for _, stmt := range block.Statements {
		if variable, ok := stmt.(*ontamaAST.VariableDecl); ok {
			if propagated, ok := variable.Value.(*ontamaAST.PropagateExpr); ok {
				generated, err := generatePropagationStatements(propagated, variable)
				if err != nil {
					return nil, err
				}
				result.List = append(result.List, generated...)
				if !variable.Used {
					result.List = append(result.List, &goast.AssignStmt{
						Lhs: []goast.Expr{goast.NewIdent("_")}, Tok: token.ASSIGN,
						Rhs: []goast.Expr{goast.NewIdent(goName(variable.Name))},
					})
				}
				continue
			}
		}
		if expression, ok := stmt.(*ontamaAST.ExpressionStmt); ok {
			if propagated, ok := expression.Value.(*ontamaAST.PropagateExpr); ok {
				generated, err := generatePropagationStatements(propagated, nil)
				if err != nil {
					return nil, err
				}
				result.List = append(result.List, generated...)
				continue
			}
		}
		generated, err := generateStatement(stmt)
		if err != nil {
			return nil, err
		}
		result.List = append(result.List, generated)
		if variable, ok := stmt.(*ontamaAST.VariableDecl); ok && !variable.Used {
			result.List = append(result.List, &goast.AssignStmt{
				Lhs: []goast.Expr{goast.NewIdent("_")}, Tok: token.ASSIGN,
				Rhs: []goast.Expr{goast.NewIdent(goName(variable.Name))},
			})
		}
		if declaration, ok := stmt.(*ontamaAST.MultiVariableDecl); ok {
			for _, binding := range declaration.Bindings {
				if binding.Name == "_" || binding.Used {
					continue
				}
				result.List = append(result.List, &goast.AssignStmt{
					Lhs: []goast.Expr{goast.NewIdent("_")}, Tok: token.ASSIGN,
					Rhs: []goast.Expr{goast.NewIdent(goName(binding.Name))},
				})
			}
		}
	}
	return result, nil
}

func functionResults(ref ontamaAST.TypeRef) *goast.FieldList {
	if ref.Name == "void" {
		return nil
	}
	if ref.Name == "Result" && len(ref.GenericArguments) == 1 {
		element := ref.GenericArguments[0]
		fields := []*goast.Field{}
		if element.Name != "void" {
			fields = append(fields, &goast.Field{Type: goType(element)})
		}
		fields = append(fields, &goast.Field{Type: goast.NewIdent("error")})
		return &goast.FieldList{List: fields}
	}
	return &goast.FieldList{List: []*goast.Field{{Type: goType(ref)}}}
}

func generateResultReturn(stmt *ontamaAST.ReturnStmt) (goast.Stmt, error) {
	call, isCall := stmt.Value.(*ontamaAST.CallExpr)
	switch stmt.ResultKind {
	case ontamaAST.ResultSuccessReturn:
		if !isCall || call.Builtin != ontamaAST.ResultOKCall {
			return nil, fmt.Errorf("Result success return has an invalid expression")
		}
		results := []goast.Expr{}
		if stmt.ResultType.Name != "void" {
			if len(call.Arguments) != 1 {
				return nil, fmt.Errorf("non-void Result success requires one value")
			}
			value, err := generateExpression(call.Arguments[0])
			if err != nil {
				return nil, err
			}
			results = append(results, value)
		}
		results = append(results, goast.NewIdent("nil"))
		return &goast.ReturnStmt{Results: results}, nil
	case ontamaAST.ResultFailureReturn:
		if !isCall || call.Builtin != ontamaAST.ResultFailCall || len(call.Arguments) != 1 {
			return nil, fmt.Errorf("Result failure return requires one error")
		}
		errorValue, err := generateExpression(call.Arguments[0])
		if err != nil {
			return nil, err
		}
		results := []goast.Expr{}
		if stmt.ResultType.Name != "void" {
			results = append(results, zeroValue(stmt.ResultType))
		}
		results = append(results, errorValue)
		return &goast.ReturnStmt{Results: results}, nil
	case ontamaAST.ResultForwardReturn:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		return &goast.ReturnStmt{Results: []goast.Expr{value}}, nil
	default:
		return nil, fmt.Errorf("unknown Result return kind %d", stmt.ResultKind)
	}
}

func generateExceptionReturn(stmt *ontamaAST.ReturnStmt) (goast.Stmt, error) {
	returnPanic := func(value, errValue goast.Expr) goast.Stmt {
		fields := []goast.Expr{}
		if value != nil {
			fields = append(fields, &goast.KeyValueExpr{Key: goast.NewIdent("value"), Value: value})
		}
		if errValue != nil {
			fields = append(fields, &goast.KeyValueExpr{Key: goast.NewIdent("err"), Value: errValue})
		}
		return &goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent("panic"), Args: []goast.Expr{
			&goast.CompositeLit{Type: goast.NewIdent("__ontamaReturn"), Elts: fields},
		}}}
	}

	if stmt.ResultKind == ontamaAST.NormalReturn {
		if stmt.Value == nil {
			return returnPanic(nil, nil), nil
		}
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		return returnPanic(value, nil), nil
	}

	call, isCall := stmt.Value.(*ontamaAST.CallExpr)
	switch stmt.ResultKind {
	case ontamaAST.ResultSuccessReturn:
		if !isCall || call.Builtin != ontamaAST.ResultOKCall {
			return nil, fmt.Errorf("Result success return has an invalid expression")
		}
		if stmt.ResultType.Name == "void" {
			return returnPanic(nil, goast.NewIdent("nil")), nil
		}
		if len(call.Arguments) != 1 {
			return nil, fmt.Errorf("non-void Result success requires one value")
		}
		value, err := generateExpression(call.Arguments[0])
		if err != nil {
			return nil, err
		}
		return returnPanic(value, goast.NewIdent("nil")), nil
	case ontamaAST.ResultFailureReturn:
		if !isCall || call.Builtin != ontamaAST.ResultFailCall || len(call.Arguments) != 1 {
			return nil, fmt.Errorf("Result failure return requires one error")
		}
		errorValue, err := generateExpression(call.Arguments[0])
		if err != nil {
			return nil, err
		}
		return returnPanic(nil, errorValue), nil
	case ontamaAST.ResultForwardReturn:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		body := &goast.BlockStmt{}
		if stmt.ResultType.Name == "void" {
			body.List = append(body.List,
				&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent("err")}, Tok: token.DEFINE, Rhs: []goast.Expr{value}},
				returnPanic(nil, goast.NewIdent("err")),
			)
		} else {
			body.List = append(body.List,
				&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent("value"), goast.NewIdent("err")}, Tok: token.DEFINE, Rhs: []goast.Expr{value}},
				returnPanic(goast.NewIdent("value"), goast.NewIdent("err")),
			)
		}
		return &goast.ExprStmt{X: &goast.CallExpr{Fun: &goast.FuncLit{Type: &goast.FuncType{Params: &goast.FieldList{}}, Body: body}}}, nil
	default:
		return nil, fmt.Errorf("unknown Result return kind %d", stmt.ResultKind)
	}
}

func generatePropagationStatements(expr *ontamaAST.PropagateExpr, variable *ontamaAST.VariableDecl) ([]goast.Stmt, error) {
	value, err := generateExpression(expr.Value)
	if err != nil {
		return nil, err
	}
	errorName := expr.ErrorName
	if errorName == "" {
		errorName = fmt.Sprintf("__ontama_result_error_%d", expr.Span.Start.Offset)
	}
	names := []*goast.Ident{}
	valueName := ""
	explicitType := variable != nil && variable.Type.IsSpecified()
	if expr.ValueType.Name != "void" {
		if variable == nil {
			return nil, fmt.Errorf("non-void result propagation requires a variable")
		}
		valueName = goName(variable.Name)
		if explicitType {
			valueName = fmt.Sprintf("__ontama_result_value_%d", expr.Span.Start.Offset)
		}
		names = append(names, goast.NewIdent(valueName))
	}
	names = append(names, goast.NewIdent(errorName))
	declaration := &goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{
		Names: names, Values: []goast.Expr{value},
	}}}}
	results := []goast.Expr{}
	if expr.ResultType.Name != "void" {
		results = append(results, zeroValue(expr.ResultType))
	}
	results = append(results, goast.NewIdent(errorName))
	propagate := &goast.IfStmt{
		Cond: &goast.BinaryExpr{X: goast.NewIdent(errorName), Op: token.NEQ, Y: goast.NewIdent("nil")},
		Body: &goast.BlockStmt{List: []goast.Stmt{&goast.ReturnStmt{Results: results}}},
	}
	statements := []goast.Stmt{declaration, propagate}
	if explicitType && expr.ValueType.Name != "void" {
		binding := &goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{
			Names: []*goast.Ident{goast.NewIdent(goName(variable.Name))}, Type: goType(variable.Type), Values: []goast.Expr{goast.NewIdent(valueName)},
		}}}}
		statements = append(statements, binding)
	}
	return statements, nil
}

func zeroValue(ref ontamaAST.TypeRef) goast.Expr {
	return &goast.StarExpr{X: &goast.CallExpr{Fun: goast.NewIdent("new"), Args: []goast.Expr{goType(ref)}}}
}

func generateStatement(stmt ontamaAST.Statement) (goast.Stmt, error) {
	switch stmt := stmt.(type) {
	case *ontamaAST.VariableDecl:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		tok := token.VAR
		if stmt.Constant && isGoConstant(stmt.Value) {
			tok = token.CONST
		}
		spec := &goast.ValueSpec{Names: []*goast.Ident{goast.NewIdent(goName(stmt.Name))}, Values: []goast.Expr{value}}
		if stmt.Type.Name != "" || stmt.Type.IsFunction() || stmt.Type.IsPointer() {
			spec.Type = goType(stmt.Type)
		}
		return &goast.DeclStmt{Decl: &goast.GenDecl{Tok: tok, Specs: []goast.Spec{spec}}}, nil
	case *ontamaAST.MultiVariableDecl:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		names := make([]*goast.Ident, len(stmt.Bindings))
		for i, binding := range stmt.Bindings {
			names[i] = goast.NewIdent(goName(binding.Name))
		}
		spec := &goast.ValueSpec{Names: names, Values: []goast.Expr{value}}
		return &goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{spec}}}, nil
	case *ontamaAST.ReturnStmt:
		if stmt.CrossesTry {
			return generateExceptionReturn(stmt)
		}
		if stmt.ResultKind != ontamaAST.NormalReturn {
			return generateResultReturn(stmt)
		}
		result := &goast.ReturnStmt{}
		if stmt.Value != nil {
			value, err := generateExpression(stmt.Value)
			if err != nil {
				return nil, err
			}
			result.Results = []goast.Expr{value}
		}
		return result, nil
	case *ontamaAST.ThrowStmt:
		if stmt.Bare {
			return &goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent("panic"), Args: []goast.Expr{
				goast.NewIdent(fmt.Sprintf("__ontama_thrown_%d", stmt.RethrowOffset)),
			}}}, nil
		}
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		thrown := &goast.CompositeLit{Type: goast.NewIdent("__ontamaThrown"), Elts: []goast.Expr{
			&goast.KeyValueExpr{Key: goast.NewIdent("err"), Value: value},
		}}
		return &goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent("panic"), Args: []goast.Expr{thrown}}}, nil
	case *ontamaAST.TryStmt:
		return generateTryStatement(stmt)
	case *ontamaAST.IfStmt:
		condition, err := generateExpression(stmt.Condition)
		if err != nil {
			return nil, err
		}
		then, err := generateBlock(stmt.Then)
		if err != nil {
			return nil, err
		}
		result := &goast.IfStmt{Cond: condition, Body: then}
		if stmt.Else != nil {
			result.Else, err = generateStatement(stmt.Else)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	case *ontamaAST.BlockStmt:
		return generateBlock(stmt)
	case *ontamaAST.ExpressionStmt:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		return &goast.ExprStmt{X: value}, nil
	case *ontamaAST.AssignmentStmt:
		target, err := generateExpression(stmt.Target)
		if err != nil {
			return nil, err
		}
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		return &goast.AssignStmt{Lhs: []goast.Expr{target}, Tok: goAssignmentToken(stmt.Operator), Rhs: []goast.Expr{value}}, nil
	case *ontamaAST.IncDecStmt:
		target, err := generateExpression(stmt.Target)
		if err != nil {
			return nil, err
		}
		operator := token.INC
		if stmt.Operator == "--" {
			operator = token.DEC
		}
		return &goast.IncDecStmt{X: target, Tok: operator}, nil
	case *ontamaAST.MultiAssignmentStmt:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		targets := make([]goast.Expr, len(stmt.Bindings))
		for i, binding := range stmt.Bindings {
			targets[i] = goast.NewIdent(goName(binding.Name))
		}
		return &goast.AssignStmt{Lhs: targets, Tok: token.ASSIGN, Rhs: []goast.Expr{value}}, nil
	case *ontamaAST.WhileStmt:
		condition, err := generateExpression(stmt.Condition)
		if err != nil {
			return nil, err
		}
		body, err := generateBlock(stmt.Body)
		if err != nil {
			return nil, err
		}
		return &goast.ForStmt{Cond: condition, Body: body}, nil
	case *ontamaAST.ForStmt:
		result := &goast.ForStmt{}
		var err error
		if stmt.Initializer != nil {
			result.Init, err = generateForClause(stmt.Initializer, true)
			if err != nil {
				return nil, err
			}
		}
		if stmt.Condition != nil {
			result.Cond, err = generateExpression(stmt.Condition)
			if err != nil {
				return nil, err
			}
		}
		if stmt.Post != nil {
			result.Post, err = generateForClause(stmt.Post, false)
			if err != nil {
				return nil, err
			}
		}
		result.Body, err = generateBlock(stmt.Body)
		if err != nil {
			return nil, err
		}
		return result, nil
	case *ontamaAST.ForRangeStmt:
		source, err := generateExpression(stmt.Source)
		if err != nil {
			return nil, err
		}
		body, err := generateBlock(stmt.Body)
		if err != nil {
			return nil, err
		}
		result := &goast.RangeStmt{X: source, Body: body}
		for index := len(stmt.Bindings) - 1; index >= 0; index-- {
			binding := stmt.Bindings[index]
			if binding.Name == "_" || !binding.Assigned || binding.Used {
				continue
			}
			body.List = append([]goast.Stmt{&goast.AssignStmt{
				Lhs: []goast.Expr{goast.NewIdent("_")}, Tok: token.ASSIGN,
				Rhs: []goast.Expr{goast.NewIdent(goName(binding.Name))},
			}}, body.List...)
		}
		if stmt.Kind == ontamaAST.ChannelRange {
			if len(stmt.Bindings) == 1 && rangeBindingNeeded(stmt.Bindings[0]) {
				result.Key = goast.NewIdent(goName(stmt.Bindings[0].Name))
				result.Tok = token.DEFINE
			}
			return result, nil
		}
		if len(stmt.Bindings) == 1 {
			binding := stmt.Bindings[0]
			if rangeBindingNeeded(binding) {
				result.Key = goast.NewIdent("_")
				result.Value = goast.NewIdent(goName(binding.Name))
				result.Tok = token.DEFINE
			}
			return result, nil
		}
		if len(stmt.Bindings) == 2 {
			key, value := stmt.Bindings[0], stmt.Bindings[1]
			if rangeBindingNeeded(value) {
				result.Key = goast.NewIdent("_")
				if rangeBindingNeeded(key) {
					result.Key = goast.NewIdent(goName(key.Name))
				}
				result.Value = goast.NewIdent(goName(value.Name))
				result.Tok = token.DEFINE
			} else if rangeBindingNeeded(key) {
				result.Key = goast.NewIdent(goName(key.Name))
				result.Tok = token.DEFINE
			}
		}
		return result, nil
	case *ontamaAST.SelectStmt:
		body := &goast.BlockStmt{}
		for i := range stmt.Cases {
			clause, err := generateSelectCase(&stmt.Cases[i])
			if err != nil {
				return nil, err
			}
			body.List = append(body.List, clause)
		}
		return &goast.SelectStmt{Body: body}, nil
	case *ontamaAST.ValueSwitchStmt:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		body := &goast.BlockStmt{}
		for i := range stmt.Cases {
			clause, err := generateValueSwitchCase(&stmt.Cases[i])
			if err != nil {
				return nil, err
			}
			body.List = append(body.List, clause)
		}
		return &goast.SwitchStmt{Tag: value, Body: body}, nil
	case *ontamaAST.TypeSwitchStmt:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		guardName := fmt.Sprintf("__ontama_type_switch_%d", stmt.Span.Start.Offset)
		guardUsed := false
		body := &goast.BlockStmt{}
		for i := range stmt.Cases {
			guardUsed = guardUsed || stmt.Cases[i].Used
			clause, err := generateTypeSwitchCase(&stmt.Cases[i], guardName)
			if err != nil {
				return nil, err
			}
			body.List = append(body.List, clause)
		}
		assertion := &goast.TypeAssertExpr{X: value}
		var guard goast.Stmt = &goast.ExprStmt{X: assertion}
		if guardUsed {
			guard = &goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(guardName)}, Tok: token.DEFINE, Rhs: []goast.Expr{assertion}}
		}
		return &goast.TypeSwitchStmt{Assign: guard, Body: body}, nil
	case *ontamaAST.BranchStmt:
		branch := token.BREAK
		if stmt.Kind == ontamaAST.ContinueBranch {
			branch = token.CONTINUE
		} else if stmt.Kind == ontamaAST.GotoBranch {
			branch = token.GOTO
		} else if stmt.Kind == ontamaAST.FallthroughBranch {
			branch = token.FALLTHROUGH
		}
		generated := &goast.BranchStmt{Tok: branch}
		if stmt.Label != "" {
			generated.Label = goast.NewIdent(stmt.Label)
		}
		return generated, nil
	case *ontamaAST.LabeledStmt:
		statement, err := generateStatement(stmt.Statement)
		if err != nil {
			return nil, err
		}
		return &goast.LabeledStmt{Label: goast.NewIdent(stmt.Label), Stmt: statement}, nil
	case *ontamaAST.CallControlStmt:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		call, ok := value.(*goast.CallExpr)
		if !ok {
			return nil, fmt.Errorf("call-control statement at %v does not contain a call", stmt.Span.Start)
		}
		if stmt.Kind == ontamaAST.GoCall {
			return &goast.GoStmt{Call: call}, nil
		}
		return &goast.DeferStmt{Call: call}, nil
	case *ontamaAST.DetachStmt:
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		taskType := taskTypeFromAnnotation(stmt.ValueType, stmt.ResultTask, stmt.Void)
		body := &goast.BlockStmt{List: []goast.Stmt{
			&goast.ExprStmt{X: &goast.UnaryExpr{Op: token.ARROW, X: &goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("done")}}},
			&goast.IfStmt{Cond: &goast.BinaryExpr{X: &goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("panicValue")}, Op: token.NEQ, Y: goast.NewIdent("nil")}, Body: &goast.BlockStmt{List: []goast.Stmt{
				&goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent("panic"), Args: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("panicValue")}}}},
			}}},
		}}
		return &goast.GoStmt{Call: &goast.CallExpr{Fun: &goast.FuncLit{Type: &goast.FuncType{Params: &goast.FieldList{List: []*goast.Field{{Names: []*goast.Ident{goast.NewIdent("task")}, Type: taskType}}}}, Body: body}, Args: []goast.Expr{value}}}, nil
	case *ontamaAST.ChannelSendStmt:
		channel, err := generateExpression(stmt.Channel)
		if err != nil {
			return nil, err
		}
		value, err := generateExpression(stmt.Value)
		if err != nil {
			return nil, err
		}
		return &goast.SendStmt{Chan: channel, Value: value}, nil
	default:
		return nil, fmt.Errorf("unsupported statement %T", stmt)
	}
}

func generateTryStatement(stmt *ontamaAST.TryStmt) (goast.Stmt, error) {
	tryBody, err := generateBlock(stmt.Body)
	if err != nil {
		return nil, err
	}
	outerBody := &goast.BlockStmt{}
	if stmt.FinallyBody != nil {
		finallyBody, err := generateBlock(stmt.FinallyBody)
		if err != nil {
			return nil, err
		}
		outerBody.List = append(outerBody.List, &goast.DeferStmt{Call: &goast.CallExpr{Fun: &goast.FuncLit{
			Type: &goast.FuncType{Params: &goast.FieldList{}}, Body: finallyBody,
		}}})
	}
	if len(stmt.Catches) == 0 {
		outerBody.List = append(outerBody.List, tryBody.List...)
	} else {
		offset := stmt.Span.Start.Offset
		caughtName := fmt.Sprintf("__ontama_caught_%d", offset)
		handledName := fmt.Sprintf("__ontama_handled_%d", offset)
		errorName := fmt.Sprintf("__ontama_caught_error_%d", offset)
		recoveredName := fmt.Sprintf("__ontama_recovered_%d", offset)
		thrownName := fmt.Sprintf("__ontama_thrown_%d", offset)
		candidateName := fmt.Sprintf("__ontama_candidate_%d", offset)
		okName := fmt.Sprintf("__ontama_thrown_ok_%d", offset)

		outerBody.List = append(outerBody.List,
			&goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{
				Names: []*goast.Ident{goast.NewIdent(caughtName)}, Type: goast.NewIdent("bool"),
			}}}},
			&goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{
				Names: []*goast.Ident{goast.NewIdent(errorName)}, Type: goast.NewIdent("error"),
			}}}},
			&goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{
				Names: []*goast.Ident{goast.NewIdent(thrownName)}, Type: goast.NewIdent("__ontamaException"),
			}}}},
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent("_")}, Tok: token.ASSIGN, Rhs: []goast.Expr{goast.NewIdent(errorName)}},
		)

		recoveryBody := &goast.BlockStmt{List: []goast.Stmt{
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(recoveredName)}, Tok: token.DEFINE, Rhs: []goast.Expr{
				&goast.CallExpr{Fun: goast.NewIdent("recover")},
			}},
			&goast.IfStmt{Cond: &goast.BinaryExpr{X: goast.NewIdent(recoveredName), Op: token.EQL, Y: goast.NewIdent("nil")}, Body: &goast.BlockStmt{List: []goast.Stmt{
				&goast.ReturnStmt{},
			}}},
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(candidateName), goast.NewIdent(okName)}, Tok: token.DEFINE, Rhs: []goast.Expr{
				&goast.TypeAssertExpr{X: goast.NewIdent(recoveredName), Type: goast.NewIdent("__ontamaException")},
			}},
			&goast.IfStmt{Cond: &goast.UnaryExpr{Op: token.NOT, X: goast.NewIdent(okName)}, Body: &goast.BlockStmt{List: []goast.Stmt{
				&goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent("panic"), Args: []goast.Expr{goast.NewIdent(recoveredName)}}},
			}}},
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(thrownName)}, Tok: token.ASSIGN, Rhs: []goast.Expr{goast.NewIdent(candidateName)}},
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(caughtName)}, Tok: token.ASSIGN, Rhs: []goast.Expr{goast.NewIdent("true")}},
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(errorName)}, Tok: token.ASSIGN, Rhs: []goast.Expr{
				&goast.CallExpr{Fun: &goast.SelectorExpr{X: goast.NewIdent(candidateName), Sel: goast.NewIdent("OnsenTamagoExceptionError")}},
			}},
		}}
		tryBody.List = append([]goast.Stmt{&goast.DeferStmt{Call: &goast.CallExpr{Fun: &goast.FuncLit{
			Type: &goast.FuncType{Params: &goast.FieldList{}}, Body: recoveryBody,
		}}}}, tryBody.List...)
		outerBody.List = append(outerBody.List, &goast.ExprStmt{X: &goast.CallExpr{Fun: &goast.FuncLit{
			Type: &goast.FuncType{Params: &goast.FieldList{}}, Body: tryBody,
		}}})

		dispatchBody := &goast.BlockStmt{List: []goast.Stmt{
			&goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{
				Names: []*goast.Ident{goast.NewIdent(handledName)}, Type: goast.NewIdent("bool"),
			}}}},
		}}
		for index, clause := range stmt.Catches {
			if clause.Type.Qualifier == "" && clause.Type.Name == "error" {
				catchBody, err := generateTypedCatchBody(clause, handledName, goast.NewIdent("error"), goast.NewIdent(errorName))
				if err != nil {
					return nil, err
				}
				dispatchBody.List = append(dispatchBody.List, &goast.IfStmt{
					Cond: &goast.UnaryExpr{Op: token.NOT, X: goast.NewIdent(handledName)}, Body: catchBody,
				})
				continue
			}
			if len(clause.MatchingClasses) != 0 {
				for matchIndex, matchingClass := range clause.MatchingClasses {
					typedName := fmt.Sprintf("__ontama_typed_catch_%d_%d_%d", offset, index, matchIndex)
					typedOKName := fmt.Sprintf("__ontama_typed_catch_ok_%d_%d_%d", offset, index, matchIndex)
					typedTarget := goast.Expr(goast.NewIdent(typedName))
					if clause.Name == "_" || !clause.Used {
						typedTarget = goast.NewIdent("_")
					}
					bindingValue := goast.Expr(goast.NewIdent(typedName))
					if matchingClass != clause.Type.Name {
						bindingValue = &goast.CallExpr{Fun: goast.NewIdent(upcastName(matchingClass, clause.Type.Name)), Args: []goast.Expr{goast.NewIdent(typedName)}}
					}
					catchBody, err := generateTypedCatchBody(clause, handledName, goType(clause.Type), bindingValue)
					if err != nil {
						return nil, err
					}
					typeMatch := &goast.IfStmt{
						Init: &goast.AssignStmt{Lhs: []goast.Expr{typedTarget, goast.NewIdent(typedOKName)}, Tok: token.DEFINE, Rhs: []goast.Expr{
							&goast.TypeAssertExpr{X: goast.NewIdent(errorName), Type: &goast.StarExpr{X: goast.NewIdent(matchingClass)}},
						}},
						Cond: goast.NewIdent(typedOKName), Body: catchBody,
					}
					dispatchBody.List = append(dispatchBody.List, &goast.IfStmt{
						Cond: &goast.UnaryExpr{Op: token.NOT, X: goast.NewIdent(handledName)}, Body: &goast.BlockStmt{List: []goast.Stmt{typeMatch}},
					})
				}
				if clause.Type.Name == "Exception" {
					fallback := &goast.CallExpr{Fun: goast.NewIdent("__ontamaExceptionFromError"), Args: []goast.Expr{goast.NewIdent(errorName)}}
					catchBody, err := generateTypedCatchBody(clause, handledName, goType(clause.Type), fallback)
					if err != nil {
						return nil, err
					}
					dispatchBody.List = append(dispatchBody.List, &goast.IfStmt{
						Cond: &goast.UnaryExpr{Op: token.NOT, X: goast.NewIdent(handledName)}, Body: catchBody,
					})
				}
				continue
			}

			typedName := fmt.Sprintf("__ontama_typed_catch_%d_%d", offset, index)
			typedOKName := fmt.Sprintf("__ontama_typed_catch_ok_%d_%d", offset, index)
			typedTarget := goast.Expr(goast.NewIdent(typedName))
			if clause.Name == "_" || !clause.Used {
				typedTarget = goast.NewIdent("_")
			}
			catchBody, err := generateTypedCatchBody(clause, handledName, goType(clause.Type), goast.NewIdent(typedName))
			if err != nil {
				return nil, err
			}
			typeMatch := &goast.IfStmt{
				Init: &goast.AssignStmt{Lhs: []goast.Expr{typedTarget, goast.NewIdent(typedOKName)}, Tok: token.DEFINE, Rhs: []goast.Expr{
					&goast.TypeAssertExpr{X: goast.NewIdent(errorName), Type: goType(clause.Type)},
				}},
				Cond: goast.NewIdent(typedOKName), Body: catchBody,
			}
			dispatchBody.List = append(dispatchBody.List, &goast.IfStmt{
				Cond: &goast.UnaryExpr{Op: token.NOT, X: goast.NewIdent(handledName)}, Body: &goast.BlockStmt{List: []goast.Stmt{typeMatch}},
			})
		}
		dispatchBody.List = append(dispatchBody.List, &goast.IfStmt{
			Cond: &goast.UnaryExpr{Op: token.NOT, X: goast.NewIdent(handledName)}, Body: &goast.BlockStmt{List: []goast.Stmt{
				&goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent("panic"), Args: []goast.Expr{goast.NewIdent(thrownName)}}},
			}},
		})
		outerBody.List = append(outerBody.List, &goast.IfStmt{Cond: goast.NewIdent(caughtName), Body: dispatchBody})
	}

	call := goast.Stmt(&goast.ExprStmt{X: &goast.CallExpr{Fun: &goast.FuncLit{Type: &goast.FuncType{Params: &goast.FieldList{}}, Body: outerBody}}})
	if stmt.HandlesReturn {
		offset := stmt.Span.Start.Offset
		returningName := fmt.Sprintf("__ontama_returning_%d", offset)
		controlName := fmt.Sprintf("__ontama_return_%d", offset)
		recoveredName := fmt.Sprintf("__ontama_return_recovered_%d", offset)
		candidateName := fmt.Sprintf("__ontama_return_candidate_%d", offset)
		okName := fmt.Sprintf("__ontama_return_ok_%d", offset)
		returnRecoveryBody := &goast.BlockStmt{List: []goast.Stmt{
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(recoveredName)}, Tok: token.DEFINE, Rhs: []goast.Expr{&goast.CallExpr{Fun: goast.NewIdent("recover")}}},
			&goast.IfStmt{Cond: &goast.BinaryExpr{X: goast.NewIdent(recoveredName), Op: token.EQL, Y: goast.NewIdent("nil")}, Body: &goast.BlockStmt{List: []goast.Stmt{&goast.ReturnStmt{}}}},
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(candidateName), goast.NewIdent(okName)}, Tok: token.DEFINE, Rhs: []goast.Expr{&goast.TypeAssertExpr{X: goast.NewIdent(recoveredName), Type: goast.NewIdent("__ontamaReturn")}}},
			&goast.IfStmt{Cond: &goast.UnaryExpr{Op: token.NOT, X: goast.NewIdent(okName)}, Body: &goast.BlockStmt{List: []goast.Stmt{&goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent("panic"), Args: []goast.Expr{goast.NewIdent(recoveredName)}}}}}},
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(controlName)}, Tok: token.ASSIGN, Rhs: []goast.Expr{goast.NewIdent(candidateName)}},
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(returningName)}, Tok: token.ASSIGN, Rhs: []goast.Expr{goast.NewIdent("true")}},
		}}
		wrapperBody := &goast.BlockStmt{List: []goast.Stmt{
			&goast.DeferStmt{Call: &goast.CallExpr{Fun: &goast.FuncLit{Type: &goast.FuncType{Params: &goast.FieldList{}}, Body: returnRecoveryBody}}},
			call,
		}}
		returnStatement := exceptionControlReturn(stmt.ReturnType, controlName)
		call = &goast.BlockStmt{List: []goast.Stmt{
			&goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{Names: []*goast.Ident{goast.NewIdent(returningName)}, Type: goast.NewIdent("bool")}}}},
			&goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{Names: []*goast.Ident{goast.NewIdent(controlName)}, Type: goast.NewIdent("__ontamaReturn")}}}},
			&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent("_")}, Tok: token.ASSIGN, Rhs: []goast.Expr{goast.NewIdent(controlName)}},
			&goast.ExprStmt{X: &goast.CallExpr{Fun: &goast.FuncLit{Type: &goast.FuncType{Params: &goast.FieldList{}}, Body: wrapperBody}}},
			&goast.IfStmt{Cond: goast.NewIdent(returningName), Body: &goast.BlockStmt{List: []goast.Stmt{returnStatement}}},
		}}
	}
	if !stmt.Terminal {
		return call, nil
	}
	return &goast.BlockStmt{List: []goast.Stmt{call, &goast.ExprStmt{X: &goast.CallExpr{
		Fun: goast.NewIdent("panic"), Args: []goast.Expr{&goast.BasicLit{Kind: token.STRING, Value: strconv.Quote("unreachable after terminal OnsenTamago try")}},
	}}}}, nil
}

func generateTypedCatchBody(clause *ontamaAST.CatchClause, handledName string, bindingType, bindingValue goast.Expr) (*goast.BlockStmt, error) {
	catchBody, err := generateBlock(clause.Body)
	if err != nil {
		return nil, err
	}
	catchBody.List = append([]goast.Stmt{&goast.AssignStmt{
		Lhs: []goast.Expr{goast.NewIdent(handledName)}, Tok: token.ASSIGN, Rhs: []goast.Expr{goast.NewIdent("true")},
	}}, catchBody.List...)
	if clause.Name != "_" && clause.Used {
		binding := &goast.DeclStmt{Decl: &goast.GenDecl{Tok: token.VAR, Specs: []goast.Spec{&goast.ValueSpec{
			Names: []*goast.Ident{goast.NewIdent(goName(clause.Name))}, Type: bindingType, Values: []goast.Expr{bindingValue},
		}}}}
		catchBody.List = append([]goast.Stmt{binding}, catchBody.List...)
	}
	return catchBody, nil
}

func exceptionControlReturn(returnType ontamaAST.TypeRef, controlName string) goast.Stmt {
	control := func(field string) goast.Expr {
		return &goast.SelectorExpr{X: goast.NewIdent(controlName), Sel: goast.NewIdent(field)}
	}
	if returnType.Name == "void" {
		return &goast.ReturnStmt{}
	}
	if returnType.Name == "Result" && len(returnType.GenericArguments) == 1 {
		element := returnType.GenericArguments[0]
		if element.Name == "void" {
			return &goast.ReturnStmt{Results: []goast.Expr{control("err")}}
		}
		return &goast.ReturnStmt{Results: []goast.Expr{exceptionReturnValue(element, control("value")), control("err")}}
	}
	return &goast.ReturnStmt{Results: []goast.Expr{exceptionReturnValue(returnType, control("value"))}}
}

func exceptionReturnValue(valueType ontamaAST.TypeRef, value goast.Expr) goast.Expr {
	return &goast.CallExpr{Fun: &goast.IndexExpr{X: goast.NewIdent("__ontamaReturnValue"), Index: goType(valueType)}, Args: []goast.Expr{value}}
}

func generateValueSwitchCase(clause *ontamaAST.ValueSwitchCase) (*goast.CaseClause, error) {
	generated := &goast.CaseClause{}
	for _, value := range clause.Values {
		expression, err := generateExpression(value)
		if err != nil {
			return nil, err
		}
		generated.List = append(generated.List, expression)
	}
	body, err := generateBlock(clause.Body)
	if err != nil {
		return nil, err
	}
	generated.Body = body.List
	return generated, nil
}

func generateSelectCase(clause *ontamaAST.SelectCase) (*goast.CommClause, error) {
	generated := &goast.CommClause{}
	if clause.Kind == ontamaAST.SelectSend {
		channel, err := generateExpression(clause.Channel)
		if err != nil {
			return nil, err
		}
		value, err := generateExpression(clause.Value)
		if err != nil {
			return nil, err
		}
		generated.Comm = &goast.SendStmt{Chan: channel, Value: value}
	} else if clause.Kind == ontamaAST.SelectReceive {
		channel, err := generateExpression(clause.Channel)
		if err != nil {
			return nil, err
		}
		receive := &goast.UnaryExpr{Op: token.ARROW, X: channel}
		if clause.Declare {
			targets := make([]goast.Expr, len(clause.Bindings))
			used := false
			for i, binding := range clause.Bindings {
				name := "_"
				if binding.Name != "_" && binding.Used {
					name = goName(binding.Name)
					used = true
				}
				targets[i] = goast.NewIdent(name)
			}
			if used {
				generated.Comm = &goast.AssignStmt{Lhs: targets, Tok: token.DEFINE, Rhs: []goast.Expr{receive}}
			} else {
				generated.Comm = &goast.ExprStmt{X: receive}
			}
		} else if len(clause.Targets) != 0 {
			targets := make([]goast.Expr, len(clause.Targets))
			for i, target := range clause.Targets {
				targets[i], err = generateExpression(target)
				if err != nil {
					return nil, err
				}
			}
			generated.Comm = &goast.AssignStmt{Lhs: targets, Tok: token.ASSIGN, Rhs: []goast.Expr{receive}}
		} else {
			generated.Comm = &goast.ExprStmt{X: receive}
		}
	}
	body, err := generateBlock(clause.Body)
	if err != nil {
		return nil, err
	}
	generated.Body = body.List
	return generated, nil
}

func generateTypeSwitchCase(clause *ontamaAST.TypeSwitchCase, guardName string) (*goast.CaseClause, error) {
	generated := &goast.CaseClause{}
	if clause.Nil {
		generated.List = []goast.Expr{goast.NewIdent("nil")}
	} else if !clause.Default {
		generated.List = []goast.Expr{goType(clause.Type)}
	}
	body, err := generateBlock(clause.Body)
	if err != nil {
		return nil, err
	}
	if !clause.Nil && !clause.Default && clause.Name != "_" && clause.Used {
		binding := &goast.AssignStmt{
			Lhs: []goast.Expr{goast.NewIdent(goName(clause.Name))}, Tok: token.DEFINE,
			Rhs: []goast.Expr{goast.NewIdent(guardName)},
		}
		generated.Body = append(generated.Body, binding)
	}
	generated.Body = append(generated.Body, body.List...)
	return generated, nil
}

func generateForClause(stmt ontamaAST.Statement, initializer bool) (goast.Stmt, error) {
	if variable, ok := stmt.(*ontamaAST.VariableDecl); ok {
		value, err := generateExpression(variable.Value)
		if err != nil {
			return nil, err
		}
		name := goName(variable.Name)
		operator := token.DEFINE
		if !variable.Used {
			name = "_"
			operator = token.ASSIGN
		}
		return &goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(name)}, Tok: operator, Rhs: []goast.Expr{value}}, nil
	}
	if declaration, ok := stmt.(*ontamaAST.MultiVariableDecl); ok {
		value, err := generateExpression(declaration.Value)
		if err != nil {
			return nil, err
		}
		targets := make([]goast.Expr, len(declaration.Bindings))
		hasName := false
		for i, binding := range declaration.Bindings {
			name := binding.Name
			if name != "_" && !binding.Used {
				name = "_"
			}
			if name != "_" {
				hasName = true
			}
			targets[i] = goast.NewIdent(goName(name))
		}
		operator := token.DEFINE
		if !hasName {
			operator = token.ASSIGN
		}
		return &goast.AssignStmt{Lhs: targets, Tok: operator, Rhs: []goast.Expr{value}}, nil
	}
	generated, err := generateStatement(stmt)
	if err != nil {
		return nil, err
	}
	switch generated.(type) {
	case *goast.AssignStmt, *goast.IncDecStmt, *goast.ExprStmt, *goast.SendStmt:
		return generated, nil
	default:
		position := "post"
		if initializer {
			position = "initializer"
		}
		return nil, fmt.Errorf("unsupported for %s %T", position, stmt)
	}
}

func rangeBindingNeeded(binding ontamaAST.RangeBinding) bool {
	return binding.Name != "_" && (binding.Used || binding.Assigned)
}

func generateExpression(expr ontamaAST.Expression) (goast.Expr, error) {
	switch expr := expr.(type) {
	case *ontamaAST.IdentifierExpr:
		return goast.NewIdent(goName(expr.Name)), nil
	case *ontamaAST.LiteralExpr:
		if expr.Kind == ontamaAST.NilLiteral || expr.Kind == ontamaAST.NullLiteral {
			return goast.NewIdent("nil"), nil
		}
		if expr.Kind == ontamaAST.BooleanLiteral {
			return goast.NewIdent(expr.Text), nil
		}
		kind := token.INT
		switch expr.Kind {
		case ontamaAST.FloatLiteral:
			kind = token.FLOAT
		case ontamaAST.StringLiteral:
			kind = token.STRING
		}
		return &goast.BasicLit{Kind: kind, Value: expr.Text}, nil
	case *ontamaAST.UnaryExpr:
		value, err := generateExpression(expr.Operand)
		if err != nil {
			return nil, err
		}
		return &goast.UnaryExpr{Op: goToken(expr.Operator), X: value}, nil
	case *ontamaAST.BinaryExpr:
		left, err := generateExpression(expr.Left)
		if err != nil {
			return nil, err
		}
		right, err := generateExpression(expr.Right)
		if err != nil {
			return nil, err
		}
		return &goast.BinaryExpr{X: left, Op: goToken(expr.Operator), Y: right}, nil
	case *ontamaAST.GoTypeAssertionExpr:
		value, err := generateExpression(expr.Value)
		if err != nil {
			return nil, err
		}
		if expr.ClassDowncast {
			name := mustDowncastName(expr.SourceClass, expr.Type.Name)
			if expr.Checked {
				name = downcastName(expr.SourceClass, expr.Type.Name)
			}
			return &goast.CallExpr{Fun: goast.NewIdent(name), Args: []goast.Expr{value}}, nil
		}
		return &goast.TypeAssertExpr{X: value, Type: goType(expr.Type)}, nil
	case *ontamaAST.TaskStartExpr:
		return generateTaskStart(expr)
	case *ontamaAST.AwaitExpr:
		return generateAwait(expr)
	case *ontamaAST.PropagateExpr:
		return nil, fmt.Errorf("result propagation was not lowered from its statement context")
	case *ontamaAST.CallExpr:
		if expr.SuperConstructor {
			args := []goast.Expr{&goast.UnaryExpr{Op: token.AND, X: &goast.SelectorExpr{X: goast.NewIdent("this"), Sel: goast.NewIdent(expr.SuperBase)}}}
			for _, argument := range expr.Arguments {
				generated, err := generateExpression(argument)
				if err != nil {
					return nil, err
				}
				args = append(args, generated)
			}
			call := &goast.CallExpr{Fun: goast.NewIdent(initializerName(expr.SuperBase)), Args: args}
			if expr.Expanded {
				call.Ellipsis = token.Pos(1)
			}
			return call, nil
		}
		if expr.Builtin == ontamaAST.ResultOKCall || expr.Builtin == ontamaAST.ResultFailCall {
			return nil, fmt.Errorf("Result constructor was not lowered from a return statement")
		}
		if expr.Builtin == ontamaAST.CopyArrayCall || expr.Builtin == ontamaAST.ViewArrayCall {
			if len(expr.TypeArguments) != 1 || len(expr.Arguments) != 1 {
				return nil, fmt.Errorf("slice-to-array lowering received an invalid call shape")
			}
			target := goType(expr.TypeArguments[0])
			if expr.Builtin == ontamaAST.ViewArrayCall {
				target = &goast.ParenExpr{X: &goast.StarExpr{X: target}}
			}
			argument, err := generateExpression(expr.Arguments[0])
			if err != nil {
				return nil, err
			}
			return &goast.CallExpr{Fun: target, Args: []goast.Expr{argument}}, nil
		}
		if expr.Builtin == ontamaAST.MakeSliceCall || expr.Builtin == ontamaAST.MakeMapCall {
			if (expr.Builtin == ontamaAST.MakeSliceCall && len(expr.TypeArguments) != 1) || (expr.Builtin == ontamaAST.MakeMapCall && len(expr.TypeArguments) != 2) {
				return nil, fmt.Errorf("collection make lowering received invalid type arguments")
			}
			var collectionType goast.Expr
			if expr.Builtin == ontamaAST.MakeSliceCall {
				collectionType = &goast.ArrayType{Elt: goType(expr.TypeArguments[0])}
			} else {
				collectionType = &goast.MapType{Key: goType(expr.TypeArguments[0]), Value: goType(expr.TypeArguments[1])}
			}
			arguments := make([]goast.Expr, len(expr.Arguments))
			for index, argument := range expr.Arguments {
				generated, err := generateExpression(argument)
				if err != nil {
					return nil, err
				}
				arguments[index] = generated
			}
			if expr.Builtin == ontamaAST.MakeSliceCall && len(arguments) == 2 {
				// Evaluate size expressions in source order before invoking Go's make
				// intrinsic so behavior does not vary between Go toolchains.
				return orderedSliceMake(collectionType, arguments[0], arguments[1]), nil
			}
			args := append([]goast.Expr{collectionType}, arguments...)
			return &goast.CallExpr{Fun: goast.NewIdent("make"), Args: args}, nil
		}
		if expr.Builtin == ontamaAST.MakeGoChannelCall {
			if len(expr.TypeArguments) != 1 {
				return nil, fmt.Errorf("goChannel lowering requires exactly one type argument")
			}
			args := []goast.Expr{&goast.ChanType{Dir: goast.SEND | goast.RECV, Value: goType(expr.TypeArguments[0])}}
			for _, argument := range expr.Arguments {
				generated, err := generateExpression(argument)
				if err != nil {
					return nil, err
				}
				args = append(args, generated)
			}
			return &goast.CallExpr{Fun: goast.NewIdent("make"), Args: args}, nil
		}
		if expr.Builtin == ontamaAST.CloseGoChannelCall {
			args := make([]goast.Expr, len(expr.Arguments))
			for i, argument := range expr.Arguments {
				generated, err := generateExpression(argument)
				if err != nil {
					return nil, err
				}
				args[i] = generated
			}
			return &goast.CallExpr{Fun: goast.NewIdent("close"), Args: args}, nil
		}
		if expr.Builtin >= ontamaAST.LenCall && expr.Builtin <= ontamaAST.MaxCall {
			name := map[ontamaAST.BuiltinCallKind]string{
				ontamaAST.LenCall: "len", ontamaAST.CapCall: "cap", ontamaAST.AppendCall: "append", ontamaAST.CopyCall: "copy", ontamaAST.DeleteCall: "delete",
				ontamaAST.ClearCall: "clear", ontamaAST.MinCall: "min", ontamaAST.MaxCall: "max",
			}[expr.Builtin]
			args := make([]goast.Expr, len(expr.Arguments))
			for i, argument := range expr.Arguments {
				generated, err := generateExpression(argument)
				if err != nil {
					return nil, err
				}
				args[i] = generated
			}
			call := &goast.CallExpr{Fun: goast.NewIdent(name), Args: args}
			if expr.Expanded {
				call.Ellipsis = token.Pos(1)
			}
			return call, nil
		}
		callee, err := generateExpression(expr.Callee)
		if err != nil {
			return nil, err
		}
		if name, ok := callee.(*goast.Ident); ok {
			name.Name = goTypeName(name.Name)
		}
		if len(expr.TypeArguments) == 1 {
			callee = &goast.IndexExpr{X: callee, Index: goType(expr.TypeArguments[0])}
		} else if len(expr.TypeArguments) > 1 {
			indices := make([]goast.Expr, len(expr.TypeArguments))
			for i := range expr.TypeArguments {
				indices[i] = goType(expr.TypeArguments[i])
			}
			callee = &goast.IndexListExpr{X: callee, Indices: indices}
		}
		args := make([]goast.Expr, 0, len(expr.Arguments))
		for _, arg := range expr.Arguments {
			generated, err := generateExpression(arg)
			if err != nil {
				return nil, err
			}
			args = append(args, generated)
		}
		call := &goast.CallExpr{Fun: callee, Args: args}
		if expr.Expanded {
			call.Ellipsis = token.Pos(1)
		}
		return call, nil
	case *ontamaAST.ArrowExpr:
		parameters := make([]*goast.Field, 0, len(expr.Parameters))
		for _, parameter := range expr.Parameters {
			parameters = append(parameters, goParameterField(parameter))
		}
		fnType := &goast.FuncType{Params: &goast.FieldList{List: parameters}}
		fnType.Results = functionResults(expr.ResolvedReturnType)
		var body *goast.BlockStmt
		if expr.BlockBody != nil {
			generatedBody, err := generateBlock(expr.BlockBody)
			if err != nil {
				return nil, err
			}
			body = generatedBody
		} else {
			value, err := generateExpression(expr.ExpressionBody)
			if err != nil {
				return nil, err
			}
			if expr.ResolvedReturnType.Name == "void" {
				body = &goast.BlockStmt{List: []goast.Stmt{&goast.ExprStmt{X: value}}}
			} else {
				body = &goast.BlockStmt{List: []goast.Stmt{&goast.ReturnStmt{Results: []goast.Expr{value}}}}
			}
		}
		return &goast.FuncLit{Type: fnType, Body: body}, nil
	case *ontamaAST.ArrayLiteralExpr:
		elements := make([]goast.Expr, 0, len(expr.Elements))
		for _, element := range expr.Elements {
			generated, err := generateExpression(element)
			if err != nil {
				return nil, err
			}
			elements = append(elements, generated)
		}
		arrayType := &goast.ArrayType{Elt: goType(expr.ResolvedElementType)}
		if expr.Fixed {
			arrayType.Len = &goast.BasicLit{Kind: token.INT, Value: strconv.FormatInt(expr.ResolvedLength, 10)}
		}
		return &goast.CompositeLit{Type: arrayType, Elts: elements}, nil
	case *ontamaAST.ObjectLiteralExpr:
		fields := make([]*goast.Field, 0, len(expr.Fields))
		values := make([]goast.Expr, 0, len(expr.Fields))
		indices := make([]int, len(expr.Fields))
		for i := range indices {
			indices[i] = i
		}
		sort.Slice(indices, func(i, j int) bool { return expr.Fields[indices[i]].Name < expr.Fields[indices[j]].Name })
		for _, i := range indices {
			field := expr.Fields[i]
			resolvedName := expr.ResolvedFieldNames[i]
			if resolvedName == "" {
				resolvedName = field.Name
			}
			fields = append(fields, &goast.Field{
				Names: []*goast.Ident{goast.NewIdent(goName(resolvedName))}, Type: goType(expr.ResolvedFieldTypes[i]),
				Tag: &goast.BasicLit{Kind: token.STRING, Value: "`json:\"" + field.Name + "\"`"},
			})
			value, err := generateExpression(field.Value)
			if err != nil {
				return nil, err
			}
			values = append(values, &goast.KeyValueExpr{Key: goast.NewIdent(goName(resolvedName)), Value: value})
		}
		return &goast.CompositeLit{Type: &goast.StructType{Fields: &goast.FieldList{List: fields}}, Elts: values}, nil
	case *ontamaAST.GoCompositeLiteralExpr:
		fields := make([]goast.Expr, 0, len(expr.Fields))
		for index, field := range expr.Fields {
			value, err := generateExpression(field.Value)
			if err != nil {
				return nil, err
			}
			name := field.Name
			if index < len(expr.ResolvedFieldNames) && expr.ResolvedFieldNames[index] != "" {
				name = expr.ResolvedFieldNames[index]
			}
			fields = append(fields, &goast.KeyValueExpr{Key: goast.NewIdent(goName(name)), Value: value})
		}
		return &goast.CompositeLit{Type: goType(expr.Type), Elts: fields}, nil
	case *ontamaAST.MemberExpr:
		if expr.Static {
			return goast.NewIdent(goName(expr.ResolvedName)), nil
		}
		object, err := generateExpression(expr.Object)
		if err != nil {
			return nil, err
		}
		name := expr.ResolvedName
		if name == "" {
			name = expr.Name
		}
		if expr.Super {
			if expr.VirtualOwner != "" {
				name = virtualSlotName(expr.VirtualOwner, name)
			}
			return &goast.SelectorExpr{X: &goast.SelectorExpr{X: goast.NewIdent("this"), Sel: goast.NewIdent(expr.SuperBase)}, Sel: goast.NewIdent(goName(name))}, nil
		}
		if expr.VirtualDispatch {
			object = &goast.SelectorExpr{X: object, Sel: goast.NewIdent(virtualSelfName(expr.VirtualOwner))}
			name = virtualSlotName(expr.VirtualOwner, name)
		}
		return &goast.SelectorExpr{X: object, Sel: goast.NewIdent(goName(name))}, nil
	case *ontamaAST.IndexExpr:
		object, err := generateExpression(expr.Object)
		if err != nil {
			return nil, err
		}
		index, err := generateExpression(expr.Index)
		if err != nil {
			return nil, err
		}
		return &goast.IndexExpr{X: object, Index: index}, nil
	case *ontamaAST.SliceExpr:
		object, err := generateExpression(expr.Object)
		if err != nil {
			return nil, err
		}
		generateBound := func(bound ontamaAST.Expression) (goast.Expr, error) {
			if bound == nil {
				return nil, nil
			}
			return generateExpression(bound)
		}
		low, err := generateBound(expr.Low)
		if err != nil {
			return nil, err
		}
		high, err := generateBound(expr.High)
		if err != nil {
			return nil, err
		}
		max, err := generateBound(expr.Max)
		if err != nil {
			return nil, err
		}
		return &goast.SliceExpr{X: object, Low: low, High: high, Max: max, Slice3: expr.Full}, nil
	case *ontamaAST.NewExpr:
		args := make([]goast.Expr, 0, len(expr.Arguments))
		for _, argument := range expr.Arguments {
			generated, err := generateExpression(argument)
			if err != nil {
				return nil, err
			}
			args = append(args, generated)
		}
		call := &goast.CallExpr{Fun: indexedGoType(goast.NewIdent("New"+expr.ClassName), expr.TypeArguments), Args: args}
		if expr.Expanded {
			call.Ellipsis = token.Pos(1)
		}
		return call, nil
	case *ontamaAST.ClassUpcastExpr:
		value, err := generateExpression(expr.Value)
		if err != nil {
			return nil, err
		}
		return &goast.CallExpr{Fun: goast.NewIdent(upcastName(expr.SourceClass, expr.TargetClass)), Args: []goast.Expr{value}}, nil
	default:
		return nil, fmt.Errorf("unsupported expression %T", expr)
	}
}

func taskTypeFromAnnotation(value ontamaAST.TypeRef, resultTask, void bool) goast.Expr {
	if void {
		name := "__ontamaVoidTask"
		if resultTask {
			name = "__ontamaVoidResultTask"
		}
		return &goast.StarExpr{X: goast.NewIdent(name)}
	}
	name := "__ontamaTask"
	if resultTask {
		name = "__ontamaResultTask"
	}
	return &goast.StarExpr{X: &goast.IndexExpr{X: goast.NewIdent(name), Index: goType(value)}}
}

func generateTaskStart(expr *ontamaAST.TaskStartExpr) (goast.Expr, error) {
	callee, err := generateExpression(expr.Call.Callee)
	if err != nil {
		return nil, err
	}
	body := &goast.BlockStmt{List: []goast.Stmt{
		&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent("taskFunction")}, Tok: token.DEFINE, Rhs: []goast.Expr{callee}},
	}}
	argumentNames := make([]goast.Expr, 0, len(expr.Call.Arguments))
	for index, argument := range expr.Call.Arguments {
		value, argumentErr := generateExpression(argument)
		if argumentErr != nil {
			return nil, argumentErr
		}
		name := fmt.Sprintf("taskArgument%d", index)
		body.List = append(body.List, &goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent(name)}, Tok: token.DEFINE, Rhs: []goast.Expr{value}})
		argumentNames = append(argumentNames, goast.NewIdent(name))
	}
	taskType := taskTypeFromAnnotation(expr.ValueType, expr.ResultTask, expr.Void)
	concreteTaskType := taskType.(*goast.StarExpr).X
	doneChannelType := &goast.ChanType{Dir: goast.SEND | goast.RECV, Value: &goast.StructType{Fields: &goast.FieldList{}}}
	taskLiteral := &goast.CompositeLit{Type: concreteTaskType, Elts: []goast.Expr{
		&goast.KeyValueExpr{Key: goast.NewIdent("done"), Value: &goast.CallExpr{Fun: goast.NewIdent("make"), Args: []goast.Expr{doneChannelType}}},
	}}
	body.List = append(body.List, &goast.AssignStmt{
		Lhs: []goast.Expr{goast.NewIdent("task")}, Tok: token.DEFINE,
		Rhs: []goast.Expr{&goast.UnaryExpr{Op: token.AND, X: taskLiteral}},
	})
	call := &goast.CallExpr{Fun: goast.NewIdent("taskFunction"), Args: argumentNames}
	if expr.Call.Expanded {
		call.Ellipsis = token.Pos(1)
	}
	recoverBody := &goast.BlockStmt{List: []goast.Stmt{&goast.AssignStmt{
		Lhs: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("panicValue")}},
		Tok: token.ASSIGN, Rhs: []goast.Expr{&goast.CallExpr{Fun: goast.NewIdent("recover")}},
	}}}
	workerBody := &goast.BlockStmt{List: []goast.Stmt{
		&goast.DeferStmt{Call: &goast.CallExpr{Fun: goast.NewIdent("close"), Args: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("done")}}}},
		&goast.DeferStmt{Call: &goast.CallExpr{Fun: &goast.FuncLit{Type: &goast.FuncType{Params: &goast.FieldList{}}, Body: recoverBody}}},
	}}
	switch {
	case expr.ResultTask && expr.Void:
		workerBody.List = append(workerBody.List, &goast.AssignStmt{Lhs: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("err")}}, Tok: token.ASSIGN, Rhs: []goast.Expr{call}})
	case expr.ResultTask:
		workerBody.List = append(workerBody.List, &goast.AssignStmt{Lhs: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("value")}, &goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("err")}}, Tok: token.ASSIGN, Rhs: []goast.Expr{call}})
	case expr.Void:
		workerBody.List = append(workerBody.List, &goast.ExprStmt{X: call})
	default:
		workerBody.List = append(workerBody.List, &goast.AssignStmt{Lhs: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("value")}}, Tok: token.ASSIGN, Rhs: []goast.Expr{call}})
	}
	body.List = append(body.List,
		&goast.GoStmt{Call: &goast.CallExpr{Fun: &goast.FuncLit{Type: &goast.FuncType{Params: &goast.FieldList{}}, Body: workerBody}}},
		&goast.ReturnStmt{Results: []goast.Expr{goast.NewIdent("task")}},
	)
	return &goast.CallExpr{Fun: &goast.FuncLit{Type: &goast.FuncType{Params: &goast.FieldList{}, Results: &goast.FieldList{List: []*goast.Field{{Type: taskType}}}}, Body: body}}, nil
}

func generateAwait(expr *ontamaAST.AwaitExpr) (goast.Expr, error) {
	value, err := generateExpression(expr.Value)
	if err != nil {
		return nil, err
	}
	body := &goast.BlockStmt{List: []goast.Stmt{
		&goast.AssignStmt{Lhs: []goast.Expr{goast.NewIdent("task")}, Tok: token.DEFINE, Rhs: []goast.Expr{value}},
		&goast.ExprStmt{X: &goast.UnaryExpr{Op: token.ARROW, X: &goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("done")}}},
		&goast.IfStmt{Cond: &goast.BinaryExpr{X: &goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("panicValue")}, Op: token.NEQ, Y: goast.NewIdent("nil")}, Body: &goast.BlockStmt{List: []goast.Stmt{
			&goast.ExprStmt{X: &goast.CallExpr{Fun: goast.NewIdent("panic"), Args: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("panicValue")}}}},
		}}},
	}}
	results := &goast.FieldList{}
	switch {
	case expr.ResultTask && expr.Void:
		results.List = []*goast.Field{{Type: goast.NewIdent("error")}}
		body.List = append(body.List, &goast.ReturnStmt{Results: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("err")}}})
	case expr.ResultTask:
		results.List = []*goast.Field{{Type: goType(expr.ValueType)}, {Type: goast.NewIdent("error")}}
		body.List = append(body.List, &goast.ReturnStmt{Results: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("value")}, &goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("err")}}})
	case expr.Void:
		results = nil
	default:
		results.List = []*goast.Field{{Type: goType(expr.ValueType)}}
		body.List = append(body.List, &goast.ReturnStmt{Results: []goast.Expr{&goast.SelectorExpr{X: goast.NewIdent("task"), Sel: goast.NewIdent("value")}}})
	}
	return &goast.CallExpr{Fun: &goast.FuncLit{Type: &goast.FuncType{Params: &goast.FieldList{}, Results: results}, Body: body}}, nil
}

func orderedSliceMake(sliceType, length, capacity goast.Expr) goast.Expr {
	lengthName := goast.NewIdent("ontamaMakeLength")
	capacityName := goast.NewIdent("ontamaMakeCapacity")
	returnType := &goast.FieldList{List: []*goast.Field{{Type: sliceType}}}
	body := &goast.BlockStmt{List: []goast.Stmt{
		&goast.AssignStmt{
			Lhs: []goast.Expr{lengthName}, Tok: token.DEFINE, Rhs: []goast.Expr{length},
		},
		&goast.AssignStmt{
			Lhs: []goast.Expr{capacityName}, Tok: token.DEFINE, Rhs: []goast.Expr{capacity},
		},
		&goast.ReturnStmt{Results: []goast.Expr{&goast.CallExpr{
			Fun: goast.NewIdent("make"), Args: []goast.Expr{sliceType, lengthName, capacityName},
		}}},
	}}
	return &goast.CallExpr{Fun: &goast.FuncLit{
		Type: &goast.FuncType{Params: &goast.FieldList{}, Results: returnType}, Body: body,
	}}
}

func goType(ref ontamaAST.TypeRef) goast.Expr {
	if ref.Nullable {
		ref.Nullable = false
		return goType(ref)
	}
	if ref.Name == "Task" && len(ref.GenericArguments) == 1 {
		return taskGoType(ref.GenericArguments[0])
	}
	if ref.TypeParameter {
		return goast.NewIdent(ref.Name)
	}
	if ref.NativeNamed {
		return indexedGoType(goast.NewIdent(ref.Name), ref.GenericArguments)
	}
	if ref.IsPointer() {
		return &goast.StarExpr{X: goType(*ref.Pointee)}
	}
	if ref.Interface {
		return indexedGoType(goast.NewIdent(ref.Name), ref.GenericArguments)
	}
	if ref.Struct {
		return indexedGoType(goast.NewIdent(ref.Name), ref.GenericArguments)
	}
	if ref.IsArray() {
		arrayType := &goast.ArrayType{Elt: goType(*ref.Element)}
		if ref.IsFixedArray() {
			arrayType.Len = &goast.BasicLit{Kind: token.INT, Value: strconv.FormatInt(*ref.FixedLength, 10)}
		}
		return arrayType
	}
	if ref.Name == "Map" && len(ref.GenericArguments) == 2 {
		return &goast.MapType{Key: goType(ref.GenericArguments[0]), Value: goType(ref.GenericArguments[1])}
	}
	if len(ref.GenericArguments) == 1 {
		direction := goast.SEND | goast.RECV
		switch ref.Name {
		case "GoSendChannel":
			direction = goast.SEND
		case "GoReceiveChannel":
			direction = goast.RECV
		case "GoChannel":
		default:
			direction = 0
		}
		if direction != 0 {
			return &goast.ChanType{Dir: direction, Value: goType(ref.GenericArguments[0])}
		}
	}
	if ref.IsObject() {
		objectFields := append([]ontamaAST.ObjectTypeField(nil), ref.ObjectFields...)
		sort.Slice(objectFields, func(left, right int) bool { return objectFields[left].Name < objectFields[right].Name })
		fields := make([]*goast.Field, 0, len(objectFields))
		for _, field := range objectFields {
			fieldName := memberName(field.Name, ontamaAST.Public)
			generated := &goast.Field{Names: []*goast.Ident{goast.NewIdent(goName(fieldName))}, Type: goType(field.Type)}
			if field.JSONName != "" {
				generated.Tag = &goast.BasicLit{Kind: token.STRING, Value: "`json:\"" + field.JSONName + "\"`"}
			}
			fields = append(fields, generated)
		}
		return &goast.StructType{Fields: &goast.FieldList{List: fields}}
	}
	if ref.IsGoStruct() {
		fields := make([]*goast.Field, 0, len(ref.ObjectFields))
		for _, field := range ref.ObjectFields {
			generated := &goast.Field{Type: goType(field.Type)}
			if !field.GoEmbedded {
				generated.Names = []*goast.Ident{goast.NewIdent(field.Name)}
			}
			if field.GoTag != "" {
				generated.Tag = &goast.BasicLit{Kind: token.STRING, Value: strconv.Quote(field.GoTag)}
			}
			fields = append(fields, generated)
		}
		return &goast.StructType{Fields: &goast.FieldList{List: fields}}
	}
	if ref.IsFunction() {
		parameters := make([]*goast.Field, len(ref.Parameters))
		for i, parameter := range ref.Parameters {
			parameterType := goType(parameter)
			if ref.Variadic && i == len(ref.Parameters)-1 && parameter.Element != nil {
				parameterType = &goast.Ellipsis{Elt: goType(*parameter.Element)}
			}
			parameters[i] = &goast.Field{Type: parameterType}
		}
		fn := &goast.FuncType{Params: &goast.FieldList{List: parameters}}
		if ref.Return.Name != "void" {
			fn.Results = &goast.FieldList{List: []*goast.Field{{Type: goType(*ref.Return)}}}
		}
		return fn
	}
	if ref.Qualifier != "" {
		var qualified goast.Expr = &goast.SelectorExpr{X: goast.NewIdent(goName(ref.Qualifier)), Sel: goast.NewIdent(ref.Name)}
		if len(ref.GenericArguments) == 1 {
			return &goast.IndexExpr{X: qualified, Index: goType(ref.GenericArguments[0])}
		}
		if len(ref.GenericArguments) > 1 {
			arguments := make([]goast.Expr, len(ref.GenericArguments))
			for i := range ref.GenericArguments {
				arguments[i] = goType(ref.GenericArguments[i])
			}
			return &goast.IndexListExpr{X: qualified, Indices: arguments}
		}
		return qualified
	}
	if ref.Go {
		return indexedGoType(goast.NewIdent(ref.Name), ref.GenericArguments)
	}
	name := goTypeName(ref.Name)
	if isGoBuiltinType(name) {
		return goast.NewIdent(name)
	}
	return &goast.StarExpr{X: indexedGoType(goast.NewIdent(name), ref.GenericArguments)}
}

func indexedGoType(base goast.Expr, arguments []ontamaAST.TypeRef) goast.Expr {
	if len(arguments) == 1 {
		return &goast.IndexExpr{X: base, Index: goType(arguments[0])}
	}
	if len(arguments) > 1 {
		indices := make([]goast.Expr, len(arguments))
		for index := range arguments {
			indices[index] = goType(arguments[index])
		}
		return &goast.IndexListExpr{X: base, Indices: indices}
	}
	return base
}

func taskGoType(result ontamaAST.TypeRef) goast.Expr {
	resultTask := result.Name == "Result" && len(result.GenericArguments) == 1
	value := result
	if resultTask {
		value = result.GenericArguments[0]
	}
	if value.Name == "void" {
		name := "__ontamaVoidTask"
		if resultTask {
			name = "__ontamaVoidResultTask"
		}
		return &goast.StarExpr{X: goast.NewIdent(name)}
	}
	name := "__ontamaTask"
	if resultTask {
		name = "__ontamaResultTask"
	}
	return &goast.StarExpr{X: &goast.IndexExpr{X: goast.NewIdent(name), Index: goType(value)}}
}

func isGoBuiltinType(name string) bool {
	switch name {
	case "bool", "string", "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "byte", "error":
		return true
	default:
		return false
	}
}

func memberName(name string, visibility ontamaAST.Visibility) string {
	if visibility != ontamaAST.Public || name == "" {
		return name
	}
	first := []rune(name)
	first[0] = []rune(strings.ToUpper(string(first[0])))[0]
	return string(first)
}

func staticMethodName(className, methodName string, visibility ontamaAST.Visibility) string {
	if visibility == ontamaAST.Public {
		return goName(className + methodName)
	}
	return goName("__ontamaStatic" + className + methodName)
}

func goName(name string) string {
	if token.Lookup(name).IsKeyword() || isGoPredeclaredName(name) {
		return name + "_"
	}
	return name
}

func isGoPredeclaredName(name string) bool {
	switch name {
	case "append", "cap", "clear", "close", "complex", "copy", "delete", "imag", "len", "make", "max", "min", "new", "panic", "print", "println", "real", "recover":
		return true
	default:
		return false
	}
}

func goTypeName(name string) string {
	switch name {
	case "boolean":
		return "bool"
	case "float", "number", "float64":
		return "float64"
	default:
		return name
	}
}

func enumMemberGoName(enumName, memberNameValue string) string {
	return enumName + memberName(memberNameValue, ontamaAST.Public)
}

func goIntegerConstant(value string) goast.Expr {
	if strings.HasPrefix(value, "-") {
		return &goast.UnaryExpr{Op: token.SUB, X: &goast.BasicLit{Kind: token.INT, Value: strings.TrimPrefix(value, "-")}}
	}
	return &goast.BasicLit{Kind: token.INT, Value: value}
}

func goToken(operator string) token.Token {
	switch operator {
	case "+":
		return token.ADD
	case "-":
		return token.SUB
	case "*":
		return token.MUL
	case "/":
		return token.QUO
	case "%":
		return token.REM
	case "!":
		return token.NOT
	case "&":
		return token.AND
	case "|":
		return token.OR
	case "^":
		return token.XOR
	case "<<":
		return token.SHL
	case ">>":
		return token.SHR
	case "&^":
		return token.AND_NOT
	case "<-":
		return token.ARROW
	case "==", "===":
		return token.EQL
	case "!=", "!==":
		return token.NEQ
	case "<":
		return token.LSS
	case "<=":
		return token.LEQ
	case ">":
		return token.GTR
	case ">=":
		return token.GEQ
	case "&&":
		return token.LAND
	case "||":
		return token.LOR
	default:
		return token.ILLEGAL
	}
}

func goAssignmentToken(operator string) token.Token {
	switch operator {
	case "", "=":
		return token.ASSIGN
	case "+=":
		return token.ADD_ASSIGN
	case "-=":
		return token.SUB_ASSIGN
	case "*=":
		return token.MUL_ASSIGN
	case "/=":
		return token.QUO_ASSIGN
	case "%=":
		return token.REM_ASSIGN
	case "&=":
		return token.AND_ASSIGN
	case "|=":
		return token.OR_ASSIGN
	case "^=":
		return token.XOR_ASSIGN
	case "&^=":
		return token.AND_NOT_ASSIGN
	case "<<=":
		return token.SHL_ASSIGN
	case ">>=":
		return token.SHR_ASSIGN
	default:
		return token.ILLEGAL
	}
}

func isGoConstant(expr ontamaAST.Expression) bool {
	switch expr := expr.(type) {
	case *ontamaAST.LiteralExpr:
		return expr.Kind != ontamaAST.NilLiteral && expr.Kind != ontamaAST.NullLiteral
	case *ontamaAST.UnaryExpr:
		return isGoConstant(expr.Operand)
	case *ontamaAST.BinaryExpr:
		return isGoConstant(expr.Left) && isGoConstant(expr.Right)
	case *ontamaAST.CallExpr:
		name, ok := expr.Callee.(*ontamaAST.IdentifierExpr)
		if !ok || !isBuiltinConversion(name.Name) {
			return false
		}
		return !expr.Expanded && len(expr.Arguments) == 1 && isGoConstant(expr.Arguments[0])
	case *ontamaAST.MemberExpr:
		return expr.Constant
	default:
		return false
	}
}

func isBuiltinConversion(name string) bool {
	switch name {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float", "number", "float64", "byte":
		return true
	default:
		return false
	}
}
