package codegen

import (
	"strings"
	"testing"

	"github.com/puffball1567/kinmokusei/internal/lexer"
	"github.com/puffball1567/kinmokusei/internal/parser"
	"github.com/puffball1567/kinmokusei/internal/product"
	"github.com/puffball1567/kinmokusei/internal/sema"
)

func TestGenerateGolden(t *testing.T) {
	input := `
const meaning: int = 42;
function choose(flag: boolean, left: number, right: float): float64 {
  if (flag) { return left; } else { return right; }
}
`
	tokens, lexDiagnostics := lexer.Lex("golden.km", input)
	program, parseDiagnostics := parser.Parse(tokens)
	if len(lexDiagnostics)+len(parseDiagnostics) != 0 {
		t.Fatalf("frontend diagnostics: %v %v", lexDiagnostics, parseDiagnostics)
	}
	if diagnostics := sema.Check(program); len(diagnostics) != 0 {
		t.Fatalf("type diagnostics: %v", diagnostics)
	}
	generated, err := Generate(program, "sample")
	if err != nil {
		t.Fatal(err)
	}
	want := `// Code generated by ` + product.DisplayName + `. DO NOT EDIT.
package sample

const meaning int = 42

func choose(flag bool, left float64, right float64) float64 {
	if flag {
		return left
	} else {
		return right
	}
}
`
	if strings.TrimSpace(string(generated)) != strings.TrimSpace(want) {
		t.Fatalf("generated Go mismatch\n--- got ---\n%s\n--- want ---\n%s", generated, want)
	}
}

func TestGenerateExplicitConversion(t *testing.T) {
	input := `function convert(value: int): float { return float(value); }`
	tokens, _ := lexer.Lex("conversion.km", input)
	program, _ := parser.Parse(tokens)
	if diagnostics := sema.Check(program); len(diagnostics) != 0 {
		t.Fatalf("type diagnostics: %v", diagnostics)
	}
	generated, err := Generate(program, "sample")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(generated), "return float64(value)") {
		t.Fatalf("generated Go:\n%s", generated)
	}
}

func TestManglesGoKeywordsAndUsesVarForRuntimeConst(t *testing.T) {
	input := `
function value(): int { return 42; }
function package(type: int): int {
  const result: int = value();
  return type + result;
}
`
	tokens, _ := lexer.Lex("names.km", input)
	program, parseDiagnostics := parser.Parse(tokens)
	if len(parseDiagnostics) != 0 {
		t.Fatalf("parser diagnostics: %v", parseDiagnostics)
	}
	if diagnostics := sema.Check(program); len(diagnostics) != 0 {
		t.Fatalf("type diagnostics: %v", diagnostics)
	}
	generated, err := Generate(program, "sample")
	if err != nil {
		t.Fatal(err)
	}
	text := string(generated)
	for _, want := range []string{"func package_(type_ int) int", "var result int = value()", "return type_ + result"} {
		if !strings.Contains(text, want) {
			t.Errorf("generated Go does not contain %q:\n%s", want, text)
		}
	}
}

func TestGeneratesArrowFunctionAsGoFunctionLiteral(t *testing.T) {
	input := `
function apply(value: int, operation: (value: int) => int): int {
  return operation(value);
}
function compute(): int {
  const double = (value: int) => value * 2;
  return apply(21, double);
}
`
	tokens, _ := lexer.Lex("arrow.km", input)
	program, parseDiagnostics := parser.Parse(tokens)
	if len(parseDiagnostics) != 0 {
		t.Fatalf("parser diagnostics: %v", parseDiagnostics)
	}
	if diagnostics := sema.Check(program); len(diagnostics) != 0 {
		t.Fatalf("type diagnostics: %v", diagnostics)
	}
	generated, err := Generate(program, "sample")
	if err != nil {
		t.Fatal(err)
	}
	text := string(generated)
	for _, want := range []string{"operation func(int) int", "var double = func(value int) int", "return value * 2", "return apply(21, double)"} {
		if !strings.Contains(text, want) {
			t.Errorf("generated Go does not contain %q:\n%s", want, text)
		}
	}
}

func TestGeneratesAssignmentsAndLoops(t *testing.T) {
	input := `
function sum(limit: int): int {
  let total = 0;
  for (let index: int = 0; index < limit; index = index + 1) {
    total = total + index;
  }
  while (total < 10) { total = total + 1; }
  return total;
}
`
	tokens, _ := lexer.Lex("loops.km", input)
	program, parseDiagnostics := parser.Parse(tokens)
	if len(parseDiagnostics) != 0 {
		t.Fatalf("parser diagnostics: %v", parseDiagnostics)
	}
	if diagnostics := sema.Check(program); len(diagnostics) != 0 {
		t.Fatalf("type diagnostics: %v", diagnostics)
	}
	generated, err := Generate(program, "sample")
	if err != nil {
		t.Fatal(err)
	}
	text := string(generated)
	for _, want := range []string{"for index := 0; index < limit; index = index + 1", "for total < 10", "total = total + index"} {
		if !strings.Contains(text, want) {
			t.Errorf("generated Go does not contain %q:\n%s", want, text)
		}
	}
}

func TestGeneratesCollectionsObjectsAndClasses(t *testing.T) {
	input := `
class Counter {
  constructor(private value: int) {}
  public static function create(value: int): Counter { return new Counter(value); }
  public function increment(): void { this.value = this.value + 1; }
  public function current(): int { return this.value; }
}
function compute(): int {
  const counter = Counter.create(1);
  let values: int[] = [];
  values = [counter.current(), 2];
  const dto = { count: values[0], label: "ok" };
  return dto.count;
}
`
	tokens, _ := lexer.Lex("class.km", input)
	program, parseDiagnostics := parser.Parse(tokens)
	if len(parseDiagnostics) != 0 {
		t.Fatalf("parser diagnostics: %v", parseDiagnostics)
	}
	if diagnostics := sema.Check(program); len(diagnostics) != 0 {
		t.Fatalf("type diagnostics: %v", diagnostics)
	}
	generated, err := Generate(program, "sample")
	if err != nil {
		t.Fatal(err)
	}
	text := string(generated)
	for _, want := range []string{"type Counter struct", "func NewCounter(value int) *Counter", "func CounterCreate(value int) *Counter", "func (this *Counter) Increment()", "CounterCreate(1)", "[]int{}", "counter.Current()", "dto.Count"} {
		if !strings.Contains(text, want) {
			t.Errorf("generated Go does not contain %q:\n%s", want, text)
		}
	}
}

func TestGeneratesGoInterfaceAndConformanceAssertion(t *testing.T) {
	input := `
interface Formatter { function format(value: string): string; }
class PrefixFormatter implements Formatter {
  constructor(private prefix: string) {}
  public function format(value: string): string { return this.prefix + value; }
}
function render(formatter: Formatter, value: string): string { return formatter.format(value); }
`
	tokens, _ := lexer.Lex("interface.km", input)
	program, parseDiagnostics := parser.Parse(tokens)
	if len(parseDiagnostics) != 0 {
		t.Fatalf("parser diagnostics: %v", parseDiagnostics)
	}
	if diagnostics := sema.Check(program); len(diagnostics) != 0 {
		t.Fatalf("type diagnostics: %v", diagnostics)
	}
	generated, err := Generate(program, "sample")
	if err != nil {
		t.Fatal(err)
	}
	text := string(generated)
	for _, want := range []string{
		"type Formatter interface", "Format(value string) string", "var _ Formatter = &PrefixFormatter{}",
		"func render(formatter Formatter, value string) string", "return formatter.Format(value)",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("generated Go does not contain %q:\n%s", want, text)
		}
	}
}
