package sema

import (
	"strings"
	"testing"
)

func TestSemanticSuccessMatrix(t *testing.T) {
	tests := []struct {
		name   string
		source string
	}{
		{"primitive values", `function values(flag: boolean, text: string, a: int, b: int32, c: int64, d: float32, e: float64, octet: byte): boolean { const n: number = e; const f: float = n; return flag && text == "ok" && a < 2 && b <= 3 && c >= 4 && d > float32(0.5) && f !== 0.0 && octet == 1; }`},
		{"numeric conversions", `function convert(value: int): float { const wide: int64 = int64(value); const small: int32 = int32(wide); const ratio: float32 = float32(small); return float(ratio); }`},
		{"Go-compatible string conversions", `import go net from "net"; function bytes(value: byte[]): string { return string(value); } function runes(value: int32[]): string { return string(value); } function rune(value: int32): string { return string(value); } function named(value: net.IP): string { return string(value); }`},
		{"numeric and boolean operators", `function math(a: int, b: int): boolean { const value = -a + +b * 2 / 1 % 3; return value == 0 || value != 1 || value === 2 || value !== 3; }`},
		{"string operators and index", `function text(value: string): byte { const combined = value + "x"; const ordered = combined >= value; return combined[0]; }`},
		{"scope and shadowing", `function scope(value: int): int { let result = value; if (true) { const result = 2; const check = result == 2; } else { let result = 3; } return result; }`},
		{"loops and optional clauses", `function loops(limit: int): int { let value = 0; while (value < limit) { value = value + 1; continue; } for (; value < limit; ) { break; } return value; }`},
		{"function values", `function invoke(operation: (value: int) => int): int { return operation(2); } function named(value: int): int { return value + 1; } function arrows(): int { const expression = (value: int) => value * 2; const block = (value: int): int => { return expression(value); }; return invoke(block) + invoke(named); }`},
		{"arrays maps and objects", `function collections(values: int[], table: Map<string, int>): int { const inferred = [1, 2]; let copy: int[] = []; copy = [values[0], table["x"]]; const dto = { count: copy[0], nested: { label: "ok" } }; return dto.count + inferred[0]; }`},
		{"classes and visibility", `class Box { private hidden: int; constructor(public value: int) { this.hidden = value; } private function secret(): int { return this.hidden; } public function get(): int { return this.secret(); } public static function create(value: int): Box { return new Box(value); } } function use(): int { return Box.create(2).get(); }`},
		{"interfaces as values and map keys", `interface Value { function get(): int; } class Box implements Value { public function get(): int { return 1; } } function read(value: Value, values: Map<Value, string>): int { const same = value === value; const label = values[value]; return value.get(); } function make(): Value { return new Box(); }`},
		{"forward declarations", `function first(): Later { return new Later(); } class Later {} interface Readable { function read(): int; } class Reader implements Readable { public function read(): int { return helper(); } } function helper(): int { return 1; }`},
		{"defer and goroutine function method and callback calls", `class Worker { public function run(): void {} } function target(value: int): int { return value; } function schedule(worker: Worker, callback: (value: int) => int): void { defer target(1); defer worker.run(); go callback(2); }`},
		{"raw Go channel direction send receive discard and nil", `function relay(input: GoReceiveChannel<int>, output: GoSendChannel<int>, bidirectional: GoChannel<int>): int { let absent: GoChannel<int> = nil; let receive: GoReceiveChannel<int> = bidirectional; let send: GoSendChannel<int> = bidirectional; output <- <-input + 1; send <- 2; <-receive; return <-receive; }`},
		{"raw Go channel creation close checked binding and assignment", `function channels(): boolean { const channel = goChannel[int](2); channel <- 1; channel <- 2; const [first, firstOpen] = <-channel; let second = 0; let secondOpen = false; [second, secondOpen] = <-channel; closeGoChannel(channel); return firstOpen && secondOpen && first + second === 3; }`},
		{"unbuffered raw Go channel", `function send(channel: GoSendChannel<string>): void { channel <- "ok"; } function receive(): string { const channel = goChannel[string](); go send(channel); return <-channel; }`},
		{"channel range const let blank break and continue", `function ranges(channel: GoReceiveChannel<int>, bidirectional: GoChannel<int>): int { let total = 0; for (const value of channel) { if (value === 0) { continue; } total = total + value; if (total > 10) { break; } } for (let value: int of bidirectional) { value = value + 1; total = total + value; break; } for (const _ of bidirectional) { break; } return total; }`},
		{"slice array map string pointer and named Go collection range", `import go url from "net/url"; function ranges(items: int[], fixed: [3]int, pointer: *[3]int, table: Map<string, int>, text: string, query: url.Values): int { let total = 0; for (const value of items) { total = total + value; } for (let [index: int, value: int] of fixed) { value = value + index; total = total + value; } for (const [index, value] of pointer) { total = total + index + value; } for (const value: int of table) { total = total + value; } for (const [key: string, value: int] of table) { total = total + len(key) + value; } for (const [offset: int, rune: int32] of text) { total = total + offset + int(rune); } for (const [key, values] of query) { total = total + len(key) + len(values); } for (const [_, _] of items) {} return total; }`},
		{"channel select receive send declarations assignments blanks discard default and branch", `function choose(input: GoReceiveChannel<int>, output: GoSendChannel<int>, channel: GoChannel<int>): int { let assigned = 0; let open = false; select { case const value = <-input { return value; } case let [value, ok] = <-channel { value = value + 1; if (ok) { return value; } } case const [_, _] = <-channel {} case assigned = <-channel { return assigned; } case [assigned, open] = <-channel { if (open) { return assigned; } } case [_, open] = <-channel {} case output <- assigned { break; } case <-input {} default {} } return assigned; } function loopSelect(): void { while (true) { select { default { continue; } } } } function emptySelect(): int { select {} }`},
		{"channel select index and pointer receive targets", `function assign(input: GoReceiveChannel<int>, values: Map<string, int>, pointer: *int): void { select { case values["item"] = <-input {} default {} } select { case *pointer = <-input {} default {} } }`},
		{"Go interface type switch typed nil default blank break and loop continue", `import go io from "io"; import go strings from "strings"; function classify(value: io.Reader): int { switch (value) { case const reader as *strings.Reader { return reader.Len(); } case let writer as io.Writer { writer = writer; return 2; } case const _ as io.Reader { break; } case nil { return 3; } default { return 4; } } return 0; } function loop(value: io.Reader): void { while (true) { switch (value) { default { continue; } } } } function empty(value: io.Reader): void { switch (value) {} }`},
		{"value switch literals expressions nil default break and loop continue", `function classify(value: int, pointer: *int): int { switch (value) { case 0 { return 1; } case 1, 2 + 1 { break; } default { return 4; } } switch (pointer) { case nil { return 5; } default {} } return 0; } function loop(value: int): void { while (true) { switch (value) { default { continue; } } } }`},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if diagnostics := checkSource(t, test.source); len(diagnostics) != 0 {
				t.Fatalf("diagnostics = %v", diagnostics)
			}
		})
	}
}

func TestSemanticFailureMatrix(t *testing.T) {
	tests := []struct {
		name   string
		source string
		want   string
	}{
		{"duplicate top level", `function value(): int { return 1; } const value = 2;`, "duplicate top-level name"},
		{"built-in top level", `function int(): void {}`, "conflicts with a built-in type"},
		{"unknown type", `function value(input: Missing): void {}`, `unknown type "Missing"`},
		{"unsupported generic", `function value(input: Box<int>): void {}`, "generic type"},
		{"map arity", `function value(input: Map<int>): void {}`, "Map expects two type arguments"},
		{"void parameter", `function value(input: void): void {}`, "parameters cannot have type void"},
		{"void variable", `function value(): void { let item: void = missing(); }`, "variables cannot have type void"},
		{"duplicate local", `function value(input: int): void { let input = 1; }`, "duplicate local name"},
		{"builtin local", `function value(): void { let string = "x"; }`, "conflicts with a built-in type"},
		{"undefined value", `function value(): int { return missing; }`, "undefined name"},
		{"undefined function", `function value(): void { missing(); }`, "undefined function"},
		{"non-callable", `function value(): void { const item = 1; item(); }`, "is not callable"},
		{"defer built-in conversion", `function value(): void { defer int(1); }`, "type conversions are not calls"},
		{"go Go-type conversion", `import go time from "time"; function value(): void { go time.Duration(1); }`, "type conversions are not calls"},
		{"send to non-channel", `function value(target: int): void { target <- 1; }`, "channel send requires a Go channel"},
		{"receive from non-channel", `function value(target: int): int { return <-target; }`, "operator <- requires a Go channel operand"},
		{"send to receive-only", `function value(target: GoReceiveChannel<int>): void { target <- 1; }`, "cannot send to receive-only"},
		{"receive from send-only", `function value(target: GoSendChannel<int>): int { return <-target; }`, "cannot receive from send-only"},
		{"channel send type", `function value(target: GoSendChannel<int>): void { target <- "wrong"; }`, "cannot use string as int"},
		{"channel missing type argument", `function value(target: GoChannel): void {}`, "expects one type argument"},
		{"channel excess type arguments", `function value(target: GoChannel<int, string>): void {}`, "expects one type argument"},
		{"void channel element", `function value(target: GoChannel<void>): void {}`, "cannot be used as a Go channel element"},
		{"checked receive binding count", `function value(target: GoReceiveChannel<int>): boolean { const [item, ok, extra] = <-target; return ok; }`, "binding count mismatch"},
		{"checked receive assignment type", `function value(target: GoReceiveChannel<int>): void { let item = "wrong"; let ok = false; [item, ok] = <-target; }`, "cannot use int as string"},
		{"incompatible channel directions", `function value(target: GoSendChannel<int>): void { let receive: GoReceiveChannel<int> = target; }`, "cannot use GoSendChannel<int> as GoReceiveChannel<int>"},
		{"channel factory missing type argument", `function value(): void { const channel = goChannel(1); }`, "expects one type argument"},
		{"channel factory excess type arguments", `function value(): void { const channel = goChannel[int, string](1); }`, "expects one type argument"},
		{"channel factory capacity type", `function value(): void { const channel = goChannel[int]("large"); }`, "capacity must be an integer"},
		{"channel factory negative capacity", `function value(): void { const channel = goChannel[int](-1); }`, "capacity cannot be negative"},
		{"channel factory negative constant expression", `function value(): void { const channel = goChannel[int](1 - 2); }`, "capacity cannot be negative"},
		{"channel factory excess capacity arguments", `function value(): void { const channel = goChannel[int](1, 2); }`, "zero or one capacity argument"},
		{"channel factory invalid element", `function value(): void { const channel = goChannel[void](); }`, "cannot be used as a Go channel element"},
		{"close non-channel", `function value(): void { closeGoChannel(1); }`, "requires a Go channel"},
		{"close receive-only channel", `function value(channel: GoReceiveChannel<int>): void { closeGoChannel(channel); }`, "cannot close receive-only"},
		{"close missing argument", `function value(): void { closeGoChannel(); }`, "expects one channel argument"},
		{"close excess arguments", `function value(left: GoChannel<int>, right: GoChannel<int>): void { closeGoChannel(left, right); }`, "expects one channel argument"},
		{"reserved channel factory name", `function goChannel(): void {}`, "conflicts with a compiler built-in"},
		{"reserved channel close name", `function value(): void { let closeGoChannel = 1; }`, "conflicts with a compiler built-in"},
		{"range over unsupported type", `function value(item: int): void { for (const value of item) {} }`, "range requires an array, slice, map, string, or receive-capable Go channel"},
		{"range over send-only channel", `function value(channel: GoSendChannel<int>): void { for (const item of channel) {} }`, "cannot range over send-only channel"},
		{"channel range pair", `function value(channel: GoReceiveChannel<int>): void { for (const [index, item] of channel) {} }`, "channel range requires exactly one binding"},
		{"range binding type mismatch", `function value(channel: GoReceiveChannel<int>): void { for (const item: string of channel) {} }`, "cannot use int as string"},
		{"slice range index type mismatch", `function value(items: int[]): void { for (const [index: string, item] of items) {} }`, "cannot use int as string"},
		{"map range key type mismatch", `function value(items: Map<string, int>): void { for (const [key: int, item] of items) {} }`, "cannot use string as int"},
		{"string range value type mismatch", `function value(text: string): void { for (const [offset, value: byte] of text) {} }`, "cannot use int32 as byte"},
		{"range duplicate binding", `function value(items: int[]): void { for (const [item, item] of items) { use(item); } }`, "duplicate local name"},
		{"range const assignment", `function value(channel: GoReceiveChannel<int>): void { for (const item of channel) { item = 2; } }`, "cannot assign to const"},
		{"range binding scope", `function value(channel: GoReceiveChannel<int>): int { for (const item of channel) {} return item; }`, `undefined name "item"`},
		{"range reserved binding", `function value(channel: GoReceiveChannel<int>): void { for (const goChannel of channel) {} }`, "conflicts with a compiler built-in"},
		{"select receive non-channel", `function value(input: int): void { select { case <-input {} } }`, "operator <- requires a Go channel operand"},
		{"select receive from send-only", `function value(input: GoSendChannel<int>): void { select { case <-input {} } }`, "cannot receive from send-only"},
		{"select send non-channel", `function value(output: int): void { select { case output <- 1 {} } }`, "channel send requires a Go channel"},
		{"select send to receive-only", `function value(output: GoReceiveChannel<int>): void { select { case output <- 1 {} } }`, "cannot send to receive-only"},
		{"select send value type", `function value(output: GoSendChannel<int>): void { select { case output <- "wrong" {} } }`, "cannot use string as int"},
		{"select duplicate default", `function value(): void { select { default {} default {} } }`, "at most one default"},
		{"select receive excess bindings", `function value(input: GoReceiveChannel<int>): void { select { case const [value, open, extra] = <-input {} } }`, "expects zero, one, or two targets"},
		{"select receive duplicate binding", `function value(input: GoReceiveChannel<int>): void { select { case const [value, value] = <-input { use(value); } } }`, "duplicate local name"},
		{"select const binding assignment", `function value(input: GoReceiveChannel<int>): void { select { case const value = <-input { value = 2; } } }`, "cannot assign to const"},
		{"select binding scope", `function read(input: GoReceiveChannel<int>): int { select { case const selected = <-input {} } return selected; }`, `undefined name "selected"`},
		{"select reserved binding", `function value(input: GoReceiveChannel<int>): void { select { case const goChannel = <-input { use(goChannel); } } }`, "conflicts with a compiler built-in"},
		{"select undefined assignment target", `function value(input: GoReceiveChannel<int>): void { select { case missing = <-input {} } }`, `undefined name "missing"`},
		{"select const assignment target", `function value(input: GoReceiveChannel<int>): void { const target = 0; select { case target = <-input {} } }`, "cannot assign to const"},
		{"select receive assignment type", `function value(input: GoReceiveChannel<int>): void { let target = "wrong"; select { case target = <-input {} } }`, "cannot use int as string"},
		{"select checked assignment open type", `function value(input: GoReceiveChannel<int>): void { let target = 0; let open = 1; select { case [target, open] = <-input {} } }`, "cannot use boolean as int"},
		{"continue in select without loop", `function value(): void { select { default { continue; } } }`, "continue may only be used inside a loop"},
		{"type switch non-interface subject", `function value(input: int): void { switch (input) { case const typed as int {} } }`, "requires a Go interface value"},
		{"type switch impossible case", `import go io from "io"; function value(input: io.Reader): void { switch (input) { case const number as int {} } }`, "cannot contain type switch case int"},
		{"type switch duplicate type", `import go io from "io"; import go strings from "strings"; function value(input: io.Reader): void { switch (input) { case const first as *strings.Reader {} case const second as *strings.Reader {} } }`, "duplicate type switch case"},
		{"type switch duplicate nil", `function value(input: error): void { switch (input) { case const typed as error {} case nil {} case nil {} } }`, "at most one nil case"},
		{"type switch duplicate default", `function value(input: error): void { switch (input) { case const typed as error {} default {} default {} } }`, "at most one default case"},
		{"type switch const assignment", `import go os from "os"; function value(input: error): void { switch (input) { case const pathError as *os.PathError { pathError = nil; } } }`, "cannot assign to const"},
		{"type switch binding scope", `import go os from "os"; function inspect(input: error): *os.PathError { switch (input) { case const pathError as *os.PathError {} } return pathError; }`, `undefined name "pathError"`},
		{"type switch unknown case type", `function value(input: error): void { switch (input) { case const typed as Missing {} } }`, `unknown type "Missing"`},
		{"type switch class case type", `class Value {} function inspect(input: error): void { switch (input) { case const typed as Value {} } }`, "cannot be represented as a Go type"},
		{"continue in type switch without loop", `function value(input: error): void { switch (input) { case const typed as error {} default { continue; } } }`, "continue may only be used inside a loop"},
		{"type switch reserved binding", `import go os from "os"; function value(input: error): void { switch (input) { case const __ontama_type_switch_1 as *os.PathError {} } }`, "conflicts with a compiler built-in"},
		{"value switch noncomparable subject", `function value(input: int[]): void { switch (input) { default {} } }`, "value switch expression type int[] is not comparable"},
		{"value switch case mismatch", `function value(input: int): void { switch (input) { case "wrong" {} } }`, "cannot use string as int"},
		{"value switch duplicate integer expression", `function value(input: int): void { switch (input) { case 3 {} case 1 + 2 {} } }`, "duplicate value switch case 3"},
		{"value switch duplicate string", `function value(input: string): void { switch (input) { case "same" {} case "same" {} } }`, "duplicate value switch case"},
		{"value switch duplicate escaped string", `function value(input: string): void { switch (input) { case "\x61" {} case "a" {} } }`, "duplicate value switch case"},
		{"value switch duplicate numeric spelling", `function value(input: float): void { switch (input) { case 1 {} case 1.00 {} } }`, "duplicate value switch case 1"},
		{"value switch duplicate nil", `function value(input: *int): void { switch (input) { case nil {} case nil {} } }`, "duplicate value switch case nil"},
		{"value switch duplicate default", `function value(input: int): void { switch (input) { default {} default {} } }`, "at most one default case"},
		{"value switch nil subject", `function value(): void { switch (nil) { case nil {} } }`, "cannot infer a concrete type from nil"},
		{"value switch fixed integer overflow", `function value(input: int32): void { switch (input) { case 2147483648 {} } }`, "cannot be represented as int32"},
		{"continue in value switch without loop", `function value(input: int): void { switch (input) { default { continue; } } }`, "continue may only be used inside a loop"},
		{"argument count", `function target(value: int): void {} function value(): void { target(); }`, "expects 1 arguments, got 0"},
		{"argument type", `function target(value: int): void {} function value(): void { target("x"); }`, "cannot use string as int"},
		{"conversion count", `function value(): int { return int(1, 2); }`, "conversion to int expects 1 argument"},
		{"invalid conversion", `function value(): int { return int("x"); }`, "cannot convert string to int"},
		{"fixed array to string conversion", `function value(input: [2]byte): string { return string(input); }`, "cannot convert [2]byte to string"},
		{"missing return value", `function value(): int { return; }`, "expected return value"},
		{"value from void", `function value(): void { return 1; }`, "void function cannot return a value"},
		{"fallthrough function", `function value(flag: boolean): int { if (flag) { return 1; } }`, "may complete without returning"},
		{"fallthrough method", `class Value { public function get(flag: boolean): int { if (flag) { return 1; } } }`, "method \"get\" may complete"},
		{"non-boolean if", `function value(): void { if (1) {} }`, "if condition must be boolean"},
		{"non-boolean while", `function value(): void { while (1) {} }`, "loop condition must be boolean"},
		{"continue outside loop", `function value(): void { continue; }`, "inside a loop"},
		{"non-call expression statement", `function value(): void { 1 + 2; }`, "only function calls"},
		{"const assignment", `function value(): void { const item = 1; item = 2; }`, "cannot assign to const"},
		{"assignment type", `function value(): void { let item = 1; item = "x"; }`, "cannot use string as int"},
		{"unary boolean", `function value(): boolean { return !1; }`, "requires a boolean operand"},
		{"unary numeric", `function value(): string { return -"x"; }`, "requires a numeric operand"},
		{"binary numeric", `function value(): int { return 1 + "x"; }`, "requires numeric operands"},
		{"float remainder", `function value(): float { return 1.5 % 1.0; }`, "requires integer operands"},
		{"mixed numeric", `function value(input: int): float { return input + 1.5; }`, "cannot mix int and float"},
		{"ordered mismatch", `function value(): boolean { return 1 < "x"; }`, "same ordered type"},
		{"comparison mismatch", `function value(): boolean { return 1 == "x"; }`, "cannot compare"},
		{"logical operands", `function value(): boolean { return 1 && 2; }`, "requires boolean operands"},
		{"empty inferred array", `function value(): void { const items = []; }`, "cannot infer the element type"},
		{"mixed array", `function value(): int[] { return [1, "x"]; }`, "cannot use string as int"},
		{"array index", `function value(items: int[]): int { return items["x"]; }`, "array index must be an integer"},
		{"string index", `function value(text: string): byte { return text[false]; }`, "string index must be an integer"},
		{"map index", `function value(items: Map<string, int>): int { return items[1]; }`, "cannot use integer literal as string"},
		{"not indexable", `function value(item: int): int { return item[0]; }`, "cannot be indexed"},
		{"duplicate object field", `function value(): int { const item = { count: 1, count: 2 }; return item.count; }`, "duplicate object field"},
		{"missing object member", `function value(): int { const item = { count: 1 }; return item.missing; }`, "has no member"},
		{"primitive member", `function value(text: string): int { return text.length; }`, "has no members"},
		{"unknown class", `function value(): Missing { return new Missing(); }`, "unknown class"},
		{"constructor count", `class Value { constructor(input: int) {} } function value(): Value { return new Value(); }`, "expects 1 arguments, got 0"},
		{"constructor type", `class Value { constructor(input: int) {} } function value(): Value { return new Value("x"); }`, "cannot use string as int"},
		{"duplicate field", `class Value { private item: int; private item: int; }`, "duplicate field"},
		{"constructor field collision", `class Value { private item: int; constructor(private item: int) {} }`, "duplicate field"},
		{"duplicate method", `class Value { public function get(): int { return 1; } public function get(): int { return 2; } }`, "duplicate method"},
		{"unknown class member", `class Value {} function use(value: Value): int { return value.missing; }`, "has no member"},
		{"missing static method", `class Value { public function get(): int { return 1; } } function use(): int { return Value.get(); }`, "has no static method"},
		{"static on instance", `class Value { public static function get(): int { return 1; } } function use(value: Value): int { return value.get(); }`, "cannot be called on an instance"},
		{"private method", `class Value { private function get(): int { return 1; } } function use(value: Value): int { return value.get(); }`, "method \"get\" is private"},
		{"this outside class", `function value(): int { return this.missing; }`, `undefined name "this"`},
		{"arrow parameter void", `function value(): void { const fn = (input: void) => 1; }`, "parameters cannot have type void"},
		{"arrow expression result", `function value(): void { const fn: (value: int) => int = (value: int): string => "x"; }`, "cannot use (int) => string as (int) => int"},
		{"arrow fallthrough", `function value(): void { const fn = (flag: boolean): int => { if (flag) { return 1; } }; }`, "arrow function may complete"},
		{"class is not interface", `class Base {} class Child implements Base {}`, "unknown interface"},
		{"implements array", `interface Value {} class Child implements Value[] {}`, "implements expects an interface name"},
		{"generated constructor collision", `class Value {} function NewValue(): int { return 1; }`, "generated Go name"},
		{"public static generated collision", `function MeterCreate(value: int): int { return value; } class Meter { public static function create(value: int): int { return value; } }`, `generated Go name "MeterCreate" collides`},
		{"private static generated collision", `function __ontamaStaticMetermagnitude(value: int): int { return value; } class Meter { private static function magnitude(value: int): int { return value; } }`, `generated Go name "__ontamaStaticMetermagnitude" collides`},
		{"generated keyword collision", `function package(): int { return 1; } function package_(): int { return 2; }`, "generated Go name"},
		{"class Go keyword", `class type {}`, "is a Go keyword"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			diagnostics := checkSource(t, test.source)
			if !strings.Contains(strings.Join(diagnostics, "\n"), test.want) {
				t.Fatalf("diagnostics = %v, want substring %q", diagnostics, test.want)
			}
		})
	}
}
