import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { collect, materialize } from './go-notices.mjs';

test('preserves complete notices, nested licenses, target identity and deterministic output', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'keika-notices-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const goroot = path.join(root, 'go');
  const dir = path.join(goroot, 'src/vendor/example/pkg');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(goroot, 'LICENSE'), 'Go license\n');
  fs.writeFileSync(path.join(goroot, 'PATENTS'), 'Patent grant\n');
  fs.writeFileSync(path.dirname(dir) + '/LICENSE', 'Vendor license\n');
  fs.writeFileSync(path.join(dir, 'NOTICE.txt'), 'Vendor notice\n');
  const source = '// Copyright 2009 The Go Authors. All rights reserved.\n// Use of this source code is governed by a BSD-style\n// license that can be found in the LICENSE file.\npackage pkg\n';
  fs.writeFileSync(path.join(dir, 'plain.go'), source);
  const special = source + '// Copyright Example Authors\n// Permission to use, copy\n// Disclaimer in full\nfunc f() {}\n';
  fs.writeFileSync(path.join(dir, 'special.go'), special);
  fs.writeFileSync(path.join(dir, 'arch.s'), '// Public domain implementation\n');
  const packages = [{ ImportPath: 'main', Module: { Main: true } }, { ImportPath: 'unsafe', Standard: true }, { ImportPath: 'vendor/example/pkg', Dir: dir, Standard: true, GoFiles: ['plain.go', 'special.go'], SFiles: ['arch.s'] }];
  const files = collect(goroot, packages, 'go1.27.0', 'linux/amd64');
  assert.equal(files.get('licenses/go/src/vendor/example/pkg/special.go.txt').toString(), special);
  assert.ok(!files.has('licenses/go/src/vendor/example/pkg/plain.go.txt'));
  assert.equal(files.get('licenses/go/src/vendor/example/LICENSE').toString(), 'Vendor license\n');
  assert.ok(files.has('licenses/go/src/vendor/example/pkg/arch.s.txt'));
  assert.match(files.get('licenses/go/INDEX.txt').toString(), /go1.27.0\nTarget: linux\/amd64/);
  assert.ok(!files.get('licenses/go/INDEX.txt').toString().includes(root));
  assert.deepEqual(collect(goroot, packages, 'go1.27.0', 'linux/amd64'), files);
  const output = path.join(root, 'output');
  materialize(files, output);
  materialize(files, output, true);
  assert.throws(() => materialize(files, output), /EEXIST/);
  fs.writeFileSync(path.join(output, 'licenses/go/LICENSE'), 'changed');
  assert.throws(() => materialize(files, output, true), /notice differs/);
  fs.rmSync(path.join(output, 'licenses/go/LICENSE'));
  assert.throws(() => materialize(files, output, true), /ENOENT/);
  assert.throws(() => collect(goroot, [{ ImportPath: 'external' }], '', ''), /requires license review/);
  assert.throws(() => collect(goroot, [{ Standard: true, Dir: root }], '', ''), /outside/);
  assert.throws(() => collect(goroot, [{ ...packages[2], SysoFiles: ['x.syso'] }], '', ''), /binary object/);
  fs.writeFileSync(path.join(goroot, 'LICENSE'), '');
  assert.throws(() => collect(goroot, packages, '', ''), /empty notice/);
});
